### ISSUE TITLE
Post Duplication

### ISSUE THREAD

**Issue by terraboops** [hachyderm/community#103]
Since the Postgres mitigation efforts today, I have noticed several duplicate posts.

Examples:
https://hachyderm.io/@SuperflySamurai/109413269725854572
https://hachyderm.io/@SuperflySamurai/109413268922191670

https://hachyderm.io/@ksmithdev/109413375255448401
https://hachyderm.io/@ksmithdev/109413373201622850

https://hachyderm.io/@awgonnerman/109413320294470289
https://hachyderm.io/@awgonnerman/109413317481620240

https://hachyderm.io/@hazelweakly/109413339356197102
https://hachyderm.io/@hazelweakly/109413337322887139

**Comment by untitaker** [comment]
I have noticed this with my own posts. It seems to me as if a retry on clientside was messing things up

**Comment by dmah42** [comment]
yes, this is likely due to some workers trying to update postgres, the update happening, but the worker timing out waiting for the response.  then the worker retries.

not sure there's much we can do about it so i'll close this, but it is an unfortunate side effect of the outage.

thanks for taking the time to report it!

**Comment by helmingstay** [comment]
@dmah42  I think this issue may be more complicated than that. The issue has dramatically expanded as instance latency has increased over the last 24 hours. I suspect that user expectations are driving some amount of double-posting. Note, I'm using the web interface on 2 different platforms: debian linux w/firefox and android Firefox beta.

When the servers are responsive, hitting the "Publish!" button leads to a UI refresh that shows the new post. Under load, there's a long wait and (in most cases) the post goes through behind the scenes but there's no UI refresh. The user is given the *impression* that the post failed (unless user manually refreshes UI or searches for new post). I believe this is leading to widespread user-initiated (but not intentional) multiple posts. 

I note that *most* of my posts have ultimately succeeded, despite lags, but a small number seem to have vanished into the ether. For the moment, I'm now in the habit of copying post contents before hitting "Publish" in case it doesn't go through.
H/T @terraboops
