### ISSUE TITLE
Unable to remove bookmarks

### ISSUE THREAD

**Issue by ahamelers** [hachyderm/community#111]
Bookmarked something, attempted to remove the bookmark but the bookmark button remains highlighted and the item remains in my bookmarks list. On phone right now but can get on a computer and report console/network errors if needed.

**Comment by quintessence** [comment]
I was able to replicate the issue in our web UI and am adding it to our internal tracking.

**Comment by quintessence** [comment]
Ok here's what I found:

- We're still experiencing some latency as we're transferring data / migrating to a service that can handle the load we're placing on it
- What this means is that some actions take a visible lag to complete

For this one in particular: although the bookmark stayed after refresh for a few moments, when I refreshed again later it _did_ remove. The event was just queuing (the queue latencies are due to our cut over to the aforementioned more robust infra). Thank you for reporting and thank you for your patience :)

**Comment by quintessence** [comment]
Head's up: going to close this issue as we're redirecting all users to parent issue #143
