### ISSUE TITLE
Notification counts are off 

### ISSUE THREAD

**Issue by oliof** [hachyderm/community#112]
I usually get shown a number at the notification bell of the web UI that does not seem to match actual notifications -- it's usually a larger number than actual notifications. Just today I had a number of 15 unread notifications shown for a single new one. Either notifications get lost or the count is off.

**Comment by quintessence** [comment]
👋 Hachyderm Mod here

FYI we were / are continuing to recover from an outage, see comment on closed issue here:

https://github.com/hachyderm/community/issues/117#issuecomment-1330033935

TLDR:

There were some issues with images and posts queuing that should be clearing up (starting at around 12:00 / noon GMT and lasting several hours due to the volume of data involved). As a results of the posts queuing and then streaming correctly there may have been some impacts to notifications as well.

We'll be able to expand on this more in a public facing announcement, I mostly wanted to confirm that 1 ) we saw this and 2 ) it is tied to another issue we worked on :) 

I'm going to close this issue for now - but if you are still experiencing issues with notifications please comment here and we'll re-open.

**Comment by oliof** [comment]
Hi,
now that hachyderm is running completely stable again, I still see occasional notification count badges that do not line up with new notifications. Since I only use the web client (on desktop and mobile) this is a minor annoyance.

**Comment by quintessence** [comment]
👋 Hello - I mostly noticed this whenever someone had Hachyderm open in multiple browser tabs. Usually the issue resolves / syncs if you do a refresh of the tab you are currently on. Can you confirm if this is the case?

**Comment by oliof** [comment]
I will check, but if this includes multiple open sessions on different devices I'd argue it is unavoidable.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
Am 6. Dez. 2022, 21:38, schrieb Quintessence :
