### ISSUE TITLE
Home timelines are still behind 

### ISSUE THREAD

**Issue by pudquick** [hachyderm/community#126]
Originally commented in #117, but that was closed and marked as resolved 8+ hours ago. But issue still seems to persist?

To be clear:
Posts from other members of hachyderm.io show up almost immediately on my Home - but for everyone else posting from another instance on my Home there is not a single post  newer than 8+ hours old.

**Comment by pudquick** [comment]
An example of what this looks like currently: two hachyderm locals with recent posts sandwiching a remote instance person I also follow
![60693451-2F8B-42F1-A13F-1D7D83C39C9C](https://user-images.githubusercontent.com/925910/204707766-16340619-03f4-4b2c-9aab-bdfbf9a8fbf7.jpeg)

Every one of my remote follows is currently still in this delayed state.

**Comment by slamp** [comment]
it's probably link to the other issue hachyderm.io have 
https://github.com/hachyderm/community/issues/127
https://github.com/hachyderm/community/issues/128
https://github.com/hachyderm/community/issues/129 

(@pudquick I have the same issues (posts from https://amicale.net/public/local [FR] arrive with ~ 5hours delay in my timeline)

**Comment by sindarina** [comment]
Yeah, it probably has to do with high latency on the Sidekiq ingress queue, which is the queue that processes all incoming messages. See also; https://github.com/hachyderm/community/issues/117

**Comment by superchromix** [comment]
Server is back up, but timelines still several hours behind.

**Comment by superchromix** [comment]
Home timelines are now more than 21 hours behind.  Try viewing the profile of a user on another instance.  Posts which are already 21 hours old do not show up when viewed from hachyderm.io.

**Comment by quintessence** [comment]
👋 Hello mod here

A couple of things: we have a migration to new infrastructure in progress. To address this question directly: since we've been working the larger migration, the queues did back up. Prior to starting today's migration we did get all the queues drained and verified that federation returned to normal. This was to ensure there weren't actions queued up when the migration was taking place. 

We're closing currently open issues related to the migration and moving our correspondence to #143 . This is to help us have one place to touch base with y'all and everyone else while the migration is ongoing :)
