### ISSUE TITLE
Image upload fails with error 500

### ISSUE THREAD

**Issue by maxfragg** [hachyderm/community#139]
Both uploading images to post as well as adding avatar pictures/headers fails at the moment.
Error 500 for posts and with the generic mastodon error page for uploading avatar/header saying "We're sorry, but something went wrong on our end."

**Comment by maxfragg** [comment]
![Screenshot_20221201-091707](https://user-images.githubusercontent.com/2656270/205020264-10f27347-e933-4e02-97ea-193e3a2bcb80.png)
See here for the screenshot

**Comment by quintessence** [comment]
👋 Mod here

Thank you for reporting this one! We have seen this behavior as part of our migration. We have a HackMD document that we're updating with our migration process, located here:

https://hackmd.io/V2Ju0o5dTN61CGLJxX7IoQ

The updates to the file are infrequent, mainly because each action takes a long time to complete. (Database migrations, etc. take a long time.)

**Comment by quintessence** [comment]
👋 Hello again

We're closing issues related to the migration and redirecting users to communicate with us through issue #143
