### ISSUE TITLE
New posts don't seem to return the proper code (but do post silently)

### ISSUE THREAD

**Issue by lexfri** [hachyderm/community#141]
I'm consistently seeing the same behavior, in both apps and the web client: New post/toot composed, press submit... and things seem to hang. Some apps throw up an error, others fail silently. The web interface tends to show the progress bar but never indicate that the post went through. Typically — though not always — the post appears.

Is there an issue returning the proper response when a post is made?

**Comment by quintessence** [comment]
👋 Mod here

Thank you for reporting this one! We have seen this behavior as part of our migration. We have a HackMD document that we're updating with our migration process, located here:

https://hackmd.io/V2Ju0o5dTN61CGLJxX7IoQ

The updates to the file are infrequent, mainly because each action takes a long time to complete. (Database migrations, etc. take a long time.)

**Comment by quintessence** [comment]
👋 FYI I'm closing this issue and migrating to the parent issue we created for our migration - please see issue #143
