### ISSUE TITLE
Desired user count?

### ISSUE THREAD

**Issue by sparky005** [hachyderm/community#146]
First of all, congratulations on the migration. The experience of using hachyderm has is SUPER fast enough and doing a more or less live migration is no easy task! Great job!

Now that that's out of the way and that y'all hopefully have some breathing room, I was hoping we could get a little more concrete insight into the long term growth goals and desired user count of this instance. With the move to the new hardware I'm not really concerned about performance issues, but some folks (like myself) probably want to have their main accounts on instances of a certain size range, and it's helpful to know what a server's target size might be when deciding whether or not to set up an account there.

Thanks again for all your hard work in running this instance, especially over the last week or so!

**Comment by krisnova** [comment]
Great call out.

At this time I have made the decision to keep registration open, and to leverage the rest of the month of December to evaluate our future plans, growth policy, and posture.

There is a lot to consider, and the last thing I want is for Hachyderm to become large/bloated/unusable because of size.

I do not believe we are at that size yet. 

I wrote some more up here that might help explain my thinking. https://community.hachyderm.io/blog/2022/12/04/growth-and-sustainability/

**Comment by sparky005** [comment]
Awesome, thank you @krisnova both for the answer here as well as the detailed blog post. I really appreciate the transparency and insight into the decisions here. Nice new site btw! That seems

I'll keep an eye on the blog for any new announcements. For now I think this question is answered and I will close the issue 👍🏽 thank you so much!
