### ISSUE TITLE
Does verification via GitHub bio actually work?

### ISSUE THREAD

**Issue by untitaker** [hachyderm/community#151]
I am trying to follow the instructions at https://github.com/hachyderm/community/blob/main/verification.md#your-github-profile to verify my github profile on hachyderm. One of the ideas there tells you to set a mastodon handle in your GitHub bio. The caveat is that the username must not overlap with a GitHub username.

So this won't work for me, because my user is `untitaker` on every platform. But now I'm curious how this works.

So I try it out with a random user. I go to https://hachyderm.io/directory, and pick a username for which I cannot find a corresponding username on GitHub for. I land on `HiltonTod`, and add `@HiltonTod@hachyderm.io` to my GitHub user bio. Sorry Tod!

After hard-refreshing the page of my profile, I inspect the source code. I see no additional rel=me link, but that is the only way to verify links on mastodon!

Now I wonder:

1. Did I do something wrong?
2. Does hachyderm.io run a modified version of mastodon to enable this form of verification?

If it's the latter, that is a misguided implementation altogether. Each server in the fediverse verifies every link on every copy of any profile they store on their own. So any modifications one does on hachyderm to link verification will only work when browsing on hachyderm.io, i.e. it doesn't if a user on another server views their profile.

**Comment by quintessence** [comment]
Verifying with GitHub _should_ work; however, we've noticed it was one of the verification paths with the least consistency (in terms of working). I've added to our backlog to get a better understanding of the underlying mechanics of how verification is supposed to work to figure out a solution - especially since some other users have reported inconsistent verification results with different domains they own (i.e. domain-a.com would verify but domain-b.com would not). We're going to keep tracking these issues with non-GitHub verification as well.

**Comment by piccolbo** [comment]
FWIW, mine worked and I am piccolbo everywhere. I added the link as my blog link, waited to be authenticated on the mastodon side, then reverted to pointing to my blog. I am not sure that is the same as "adding to bio".

**Comment by untitaker** [comment]
Antonio, that's not the verification method I am talking about. That worked for me as well. I am specifically talking about the method to use the gh bio

**Comment by piccolbo** [comment]
Ooops I thought you were open to any method. Should have read the title twice.

**Comment by quintessence** [comment]
Circling back on this one and to restate: verifying with GitHub is one where many people struggle. There is feedback on Mastodon about it as well. Unfortunately, this isn't specific to the version that we're running here on Hachyderm but something with Mastodon in general.

What I'd suggest: using the URL field rather than bio. I'm going to update the page when I migrate it to the new docs site to indicate that it seems using the bio field is inconsistent at best as it does seem that using the URL field is the more reliable method.

**Comment by quintessence** [comment]
This is in our docs queue as part of the update - closing for now. (I'm leaving open the other, more general, GH Issue about verification as it links to another issue on mastodon/mastodon about verification as a feature.)
