### ISSUE TITLE
Suspension of girlcock.club

### ISSUE THREAD

**Issue by diamondburned** [hachyderm/community#197]
Hello,

I am writing to bring to your attention the issue of the suspended instance `girlcock.club` on the [About page](https://hachyderm.io/about). While I understand that instances may be suspended for a variety of reasons, it seems that the reason for the suspension of this instance is not available.

I am writing to request further clarification on the suspension of this instance. Is it due to NSFW content, or is there some other reason for the suspension? It's understandable if the instance is simply too NSFW, however I don't think there are restrictions about seeing/following NSFW content/accounts, just boosting/posting them would be an issue. I also don't think such an instance would be blocked for any reasons such as hate speech or transphobia.

Additionally, I have noticed that there are many instances listed as "suspended" on the About page without any stated reasons, and I think it would be beneficial to provide reasoning for these instances wherever possible. It's totally understandable if the moderation team simply do not have enough time for this, but I think that should at least be clarified in the About page.

I appreciate the work that the moderators and the community have put into creating an engaging space for technology and programming discussions, and thank you to the moderation team for keeping it a tidy place!

**Comment by krisnova** [comment]
Hi everyone. 

I usually stay away from these topics however this one is especially close to me, so I have asked the other mods to let me handle this one directly. 

Some quick context that I am an openly transgender woman, who has openly NOT had GRS/SRS. I have retained my original genitals and speak freely about this in my personal, public, and professional lives. I **literally** work at GitHub and am openly communicating about this here on the same website I am responsible for keeping online. 

### Being Moderated on Twitter

In 2020 my account was permanently moderated on Twitter.com for sharing a full naked picture of me on the beach, including, yes -- my cock. Twitter viewed the content as "pornographic" and I viewed the content as "art". 

The moderation was extremely disruptive to my professional life, as all of my content shipped with a very obvious ⚠️ "SENSITIVE CONTENT" ⚠️ warning despite my content being mostly about computer science. I ended up writing a [blog on the topic](https://github.com/krisnova/kris-nova/issues/2) and 2 years later my account was eventually restored.

As far as the following is concerned:

> ..noticed that there are many instances listed as "suspended" on the About page without any stated reasons

I honestly don't know. I would defer to @quintessence and link she shared. It is my understanding that a lot of this is just a consequence of time and our need to quickly moderate without an opportunity to provide more detail. I believe her link has more and is worth reading.

### Some Resarch and Consideration

So after reading this original issue I spent about an hour researching [girlcock.club](https://girlcock.club) and I did find some content on there that I would consider 18+. Specifically the animated images of genitals and breasts often flagged as "lewd".

I spent the evening discussing this in depth with @quintessence and eventually our conversation lead me to write up [public facing documentation](https://community.hachyderm.io/docs/nsfw-policy/) on our 18+ policy and our sexual content policy just so I could respond to your issue with some clear guidance. The policy is now live, and we will begin rolling out changes and referencing it in other places as Hachyderm continues to grow. 

### Our Decision

Effective immediately Hachyderm **will** lift our ban and **will** begin federating with `girlcock.club`

However, we have made the decision to [reject media](https://github.com/mastodon/documentation/blob/master/content/en/admin/moderation.md#reject-media-reject-media) from `girlcock.club`... at least for now. 

The reason for rejecting the media is only because of the legal risk that it presents for Hachyderm at this time. There is more detail on why this is a legal risk for us, and why our medium sized instance is at a slightly higher risk of being targeted legally in the blog I linked on our community website. 

After my experience with Twitter I learned how important it is to be open and provide as much detail as possible to anyone being moderated like this, and I believe in being an agent of change for the better in this world.

So here is my promise:

> If girlcock.club is able to introduce a rule that any 18+ content on the instance should come with a content warning to the best of your moderators ability to monitor

we will lift the rejected media limitation as soon as girlcock.club can demonstrate the policy change. It can be identical or similar to our policy on the topic. We just need some legal protection. 

For example the content warnings with "lewd" in front of the content is actually fine and well within the Hachyderm rules, especially with our acknowledgement on marginalized communities.

These "lewd" posts are well within our policy to federate with. The problem is that the girlcock.club rules don't specifically call out the usage of content warnings for 18+ content.

Otherwise, in order to protect our service legally, we have to continue to reject the media for now.

**Comment by diamondburned** [comment]
> If girlcock.club is able to introduce a rule that any 18+ content on the instance should come with a content warning to the best of your moderators ability to monitor

I'm just dropping a quick note here that [the instance now has this rule](https://girlcock.club/about):

> Posts containing NSFW content or content that users may not wish to engage with must be tagged with the content warning feature.

**Comment by quintessence** [comment]
I have removed moderation from `girlcock.club` - we should be federating normally now :)
