### ISSUE TITLE
Consider curating hashtag autofill suggestions to prefer camelCase for accessibility

### ISSUE THREAD

**Issue by lee0c** [hachyderm/community#232]
### What is your suggestion?

From [this mastodon github issue](https://github.com/mastodon/mastodon/issues/20267#issuecomment-1310092250), I understand that the first instance of a hashtag is the version saved by the server for autofill, regardless of case. However, it sounds like server mods have some control over this.

To promote good practice and accessibility, it would be great if the autofill preferred camelCase when relevant.

**Comment by quintessence** [comment]
I hadn't seen this setting in the admin interface, but will certainly give it a look after the holidays to see what we can do!

**Comment by ElanHasson** [comment]
Server mods can change how hashtags are displayed  in the trends section.

**Comment by quintessence** [comment]
Ok after looking into this: it looks like this is an issue open on Mastodon that is still ongoing. I'm going to close the issue here and drop the link in for anyone who would like to partake in that discussion :) We're happy to use the features if/when they're available.

https://github.com/mastodon/mastodon/issues/20267
