### ISSUE TITLE
Friend on mastodon.social says he can't follow links to my toots on hachyderm.io

### ISSUE THREAD

**Issue by cosmicfire** [hachyderm/community#236]
### What is your question?

My friend can see me on his instance (mastodon.social), and he can see when I mention him in a toot (from hachyderm), but from that toot, he cannot follow a link to the specific microblog I sent him (on hachyderm). 

He says clicking the link logs him out (???) IDK he just joined so he may be mashing the keyboard with his fist for all I know. "Dammit jim, I'm a strategist not a doctor!" or something

Any suggestions or insights appreciated.

**Comment by quintessence** [comment]
Can you provide some of the exact links to the posts in question so we can look into it / see if we can replicate? Right now there are no moderation actions against Mastodon Social, and they aren't moderating us, so on a server level that should be fine.

**Comment by quintessence** [comment]
Going to close for now - please let us know if this issue needs to be re-opened :)

**Comment by cosmicfire** [comment]
Hi, sorry I was Holidaying... here is the link he said he couldn't access. Said it logged him out. I know sometimes when you open an external link it takes you to an instance where you aren't logged in. Could it be as simple as modifying the link?

https://hachyderm.io/@PatriciaColley/109529323398515220

**Comment by quintessence** [comment]
Oh that is actually how federation works - you are only logged into your home server. If you were to, for example, take a look at these two links:

https://infosec.exchange/@andraste/109609180995305602

https://hachyderm.io/@andraste@infosec.exchange/109609181579118473

These are both the same post by that user, but when you are viewing from your home server you are logged in and able to see, comment, boost, like, and so forth. When you view on the remote server's domain, since you are not using an account on that server, you are shown to be logged out of that server.
