### ISSUE TITLE
Remove Placeholder Accounts

### ISSUE THREAD

**Issue by rifuller** [hachyderm/community#239]
### What is your suggestion?

Many people started registering accounts with common names around November when Mastodon began to hit the news. These accounts often have no posts and are inactive. Would you consider removing these placeholder accounts to make those names available for people that would like to be active? Perhaps some rules for accounts <4 characters?  At the moment I'm going to look for another server where I can have the handle that I want but I would prefer to stay here.

**Comment by rifuller** [comment]
For myself in particular, I'm looking at:
@rf
@rich
@richard 

All registered around the same time with no profile picture, description, or posts.

**Comment by quintessence** [comment]
👋 Mod here

The way that I'm going to handle this is:

1 ) We'll (the Hachyderm team) make a policy about username / handle "parking"
2 ) Enforce based on that policy

We have had issues opened in the past that, unfortunately, it looks like releasing formerly used handles _can_ cause issues with federation. Therefore, we might be able to purge an unused account but might not be able to fully release the handle until we know more. What we know so far is that it seems like a previously registered, then "removed", handle can cause issues on the remote servers. We had a couple users email / open GH Issues (e.g. #76 ) related to this. Basically: we can remove the "parked" account from being "live" (so to speak) but we won't try and purge the handles until we find out if there's a better way to truly release the handle, otherwise the user that eventually signs up for that handle who intends to use it will potentially have a hard time having a normal user experience.

**Comment by quintessence** [comment]
I've added this to our moderation queue to make and then document the policy. Closing for now :)
