### ISSUE TITLE
Copyright and licensing status of Hachyderm posts

### ISSUE THREAD

**Issue by timbray** [hachyderm/community#240]
### What is your suggestion?

I went looking for a "terms of service" or some such to find out who has the rights to do what with everyone’s posts on Hachyderm (or really any other Masto server) and didn't come up with much.  Poking around led me to the JoinMastodon terms of service at https://discourse.joinmastodon.org/tos which look pretty decent & I am told is standard text borrowed from Discourse.

IANAL but it occurs to me that it might be nice to have a default (possibly CC) license which is provided by people who post?  I also think about an optional license choice which specifically forbids some or all flavors of crawling or automated processing.

**Comment by mattwynne** [comment]
FWIW, @tillkruss is paying a lawyer to draft ToS for https://nelson.social (based in BC, Canada). We intend to CC license those when they're done.

**Comment by timbray** [comment]
Hmm, if I type "timbray site:hachyderm.io" into Google, it finds lots and lots of stuff. After all, they're URLs, and mentioned in places outside Mastodon, and Google follows those.  However, DuckDuckGo and Bing don't seem to index anything on Hachy.

**Comment by krisnova** [comment]
I hate to "tap the sign" but we have a very unhelpful answer right now, and the best of intentions. We are asking for your **patience** and your **trust**.

https://community.hachyderm.io/blog/2022/12/04/growth-and-sustainability/#governing-body

> We are considering forming a legal entity to control Hachyderm in January 2023.

We have been advised not to engage with these types of questions until we have something legally formed. I **literally** emailed our attorney in the tab to the left of this one a few minutes. The attorney said its best practice not to put anything in writing until we have everything signed and dated with the local authorities. 

Please (seriously please) be patient with us. We are doing the labor on behalf of the community and working as fast as we can. Honestly making a big fuss about things right now makes our life more difficult. We set aside 60 days (which was advised by an attorney) as a deadline for ourselves to form an entity. This bring us into January 2023 and prevents us from fighting with the IRS for a trivial portion of operating at the tail end of 2022.

In other words, we intend to have more legal information and a well posted terms of service first thing in January.

This goes against my best judgement to share what I am about to share this early, however I suspect this will reassure anyone question our intentions.

Here is the best encapsulation of what the legal situation **will most likely look like** for Hachyderm will be in January 2023. Which means we will adopt a formal license, complete with plenty of documentation on intellectual property, trademark, copyright, and patent laws in tow.

[Nivenly Foundation Media Brief](https://docs.google.com/document/d/1vydEZ-kzwgJXFRvrAPz6tR2nH9plyMrBHGYdHamQwyU/edit#heading=h.ka17d1gzft8n) contains SOME of the answers to your questions. A lot of this is still in the mix, so please take that into consideration before sharing this broadly. Despite exciting, it is also a risk and also potentially introducing work/emotional labor for myself and the rest of those involved if it gets a lot of attention.

We do not know what license we will use for Hachyderm, and therefore cannot tell you what it is yet because literally our attorney is on a beach right now not responding to email. We have questions about how to best protect the community in his inbox and intend on following up as soon as we can.

Personally I consider myself well versed enough in intellectual property law and open source licenses to advocate for our community and ask questions directly to the attorney. However if you have specific concerns I ([@krisnova) have my Signal number posted on my Hachyderm profile and I am more than happy to talk to you about your concerns.

Please. With sugar on top. Give us until the new year to enjoy the break with our families so we can respond to you in the new year. We are excited about 2023, but we also need a break and can't really do anything more at this time.

I truly hope this doesn't come off as a "read the fucking sign" style message, but I want to be clear and respectful here. We need time. We need patience. It is going to take until January. Please. Please. Be patient with us.

**Comment by nikclayton** [comment]
> specifically forbids some or all flavors of crawling or automated processing

That's probably not realistic, https://www.zdnet.com/article/court-rules-that-data-scraping-is-legal-in-linkedin-appeal/

**Comment by krisnova** [comment]
I decided not to lock this issue because candidly I don't want to come off like a total jerk, however I trust that my response makes everyone feel good in their jellies and if it doesn't I trust that folks will trust my words that it is safe to text me on signal.
