### ISSUE TITLE
Broke profile image (from other server) (cache problem?)

### ISSUE THREAD

**Issue by Aranjedeath** [hachyderm/community#265]
Hi! 

One person I follow on another server has had a broken avatar for the time I have been on hachyderm. I finally checked out what the problem was, and we are getting a rejection at image storage. I have verified that *directly on their instance* the image shows correctly. 

Relevant links:
https://media.hachyderm.io/cache/accounts/avatars/109/362/253/362/731/939/original/625c6204433ed82f.png

contents of that "image":
`
<Error>
<Code>AccessDenied</Code>
<BucketName>hachystore-1</BucketName>
<RequestId>tx00000000000000ed1b6e7-0063c498a2-7fb4ac08-fra1b</RequestId>
<HostId>7fb4ac08-fra1b-fra1-zg02</HostId>
</Error>
`

Please let me know if I can provide further detail. I am intentionally not linking the profile itself unless that is necessary.

**Comment by quintessence** [comment]
👋 Hello, mod here

We had some image caching issues that happened _way_ back when we initially migrated our storage. Basically we were doing a real-time migration due to the time lengths involved, but the kind of migration came with its own risks. Due to the way that Mastodon works, it doesn't frequently "re-ping" for the avatar image information, which leads me to believe that the original request for the current avatar _probably_ happened during that time. We've been trying to handle any lingering requests individually (like this) as doing them in bulk would incur a lot of server resources. I will ping someone on the infra team to take a look :)

**Comment by Preskton** [comment]
Hi, @Aranjedeath - could you please let us know the domain of the user so we can attempt to refresh?

**Comment by Aranjedeath** [comment]
> Hi, @Aranjedeath - could you please let us know the domain of the user so we can attempt to refresh?

Thanks for the follow up. It is still broken but no longer relevant due to the mastodon.lol instance shutting down in the future

**Comment by quintessence** [comment]
Ah ok thank you - closing for now
