### ISSUE TITLE
Change max post length from 500 to 4000 or higher 

### ISSUE THREAD

**Issue by markcartertm** [hachyderm/community#294]
### What is your suggestion?

With multiple Mastodon sites offering longer post limits. For example, Infosec.exchange limit is 10,000. The current server post length limit of 500 is extremely small and result in people spending more time editing their post for length  than focusing on content. With Twitter offering 4000 character maximum, 500 seems to be less than ideal

**Comment by quintessence** [comment]
👋 Mod here

I can actually answer this one - changing the posting length is actually an invasive change, so in order to apply this change we'd either need to commit to running a pre-existing fork of Mastodon or forking Mastodon ourselves. We're not committing ot a fork at this time, but it is on our backlog list of wants/needs/concerns that we're using to determine if and when we reach a tipping point to consider a fork (either our own or an existing). :)
