### ISSUE TITLE
Specialized Accounts: macadminsopensource

### ISSUE THREAD

**Issue by natewalck** [hachyderm/community#328]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

The Mac Admins Open Source organization exists to empower the open source community within the Mac Admins community. We provide a centralized Github for projects, code signing and code review.

### How will you ensure the community is protected?

We also believe in peace + balance and will do everything we can to preserve it within our space and hachyderm as a whole.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
Thank you! You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

FYI we do recommend that events / projects / etc. verify with their own domain where possible so that people can see that the account is affiliated. [Our documentation for how to do this](https://community.hachyderm.io/docs/mastodon/user/verification/) and [an example of an account that has](https://hachyderm.io/@zellij).

**Comment by quintessence** [comment]
Reminder ping that you can add the URL to your bio :)

**Comment by natewalck** [comment]
I *think* this is done and ready to go.

**Comment by natewalck** [comment]
Alright, we are good to go. Thanks!
