### ISSUE TITLE
Enable editing an image's alt-text after post is published

### ISSUE THREAD

**Issue by smurthys** [hachyderm/community#342]
Please pardon my ignorance if these questions are really client-related, but I have two questions/requests on editing alt-text post publication:

1. I learned recently from a post that upgrading the server to Mastodon v4.1.0 enables editing alt-text associated with images. Is that claim true?

https://mastodon.scot/@hteasley/109849939560562182
```
For this to work, your instance has to have upgraded to v4.1.0  Check the lower left corner of your screen to see.
```

2. Hachyderm appears to be on v4.0.2. What is the plan to upgrade the instance? 

See the image embedded in: https://hachyderm.io/@smurthys/109870213567990194

Thank you

**Comment by Preskton** [comment]
Howdy, @smurthys -

As for your first question, I think that's the case based on my research.

And your second: at the moment, we don't have a specific date for a 4.1.0 upgrade. Upgrades can be a very involved process, so it might take us some time before we've upgraded. That being said, we don't want to get too far behind latest because that just makes the string of updates even harder later down the road.

It's great to know that it will add this feature -- I've needed it myself.

**Comment by smurthys** [comment]
Thanks @Preskton for the update. Given hachyderm's commitment to diversity, I hope the edit alt-text feature will be enabled soon. Too bad it requires a server update.

BTW is there a means for the community to vote on issues/features they like addressed/added: like a upvote downvote kind of thing? Such a means will open a new can of worms though.

**Comment by dmah42** [comment]
i don't know of any way for upvotes on issues, but we are getting closer to doing the 4.1.0 upgrade.  stay tuned.

**Comment by prohr** [comment]
I've also been waiting for this 4.1.* functionality since it was released almost 2 months ago (Feb 10).  Of the 67 fediverse instances with over 20000 users, only six others (besides us) are still on 4.0.2:

https://instances.social/list/advanced#lang=&allowed=&prohibited=&min-users=20000&max-users=

However, it turns out that since then, the core Mastodon devs have cut two subsequent releases due to security issues:

- 4.1.1 (Mar 16) ... which broke search
- 4.1.2 (Apr 4) ... which requires a Ruby upgrade

Hence I'm happy to continue trusting our infra team to decide when + how to finish the relevant upgrade(s) so that our overall experience is better, not worse.

**Comment by Preskton** [comment]
Howdy, folks - this is the next "big" thing on our list. We're currently working through upgrading hachyderm.wtf (our dev instance) and have hit a small snag. We've reached out to the mastodon team for help, which should get us over the line, then clear us to upgrade hachyderm.io.

Thanks for your patience.

**Comment by Preskton** [comment]
As a mini-update - we've successfully executed our update runbook on https://hachyderm.wtf, which sets us up to do the main site in the coming weeks. wtf is now on 4.1.2 🎉

**Comment by Preskton** [comment]
Howdy, folks - we're now on 4.1.2. Closing this, please re-open if you have any issues/questions.

**Comment by smurthys** [comment]
Awesome. It's great to be able to edit alt-text after publishing a post. Thanks again to all who made this possible.
