### ISSUE TITLE
PROPOSED RULE: Sexually Explicit Content Not Behind a CW is Prohibited

### ISSUE THREAD

**Issue by benwis** [hachyderm/community#35]
Recently we've seen a number of accounts created solely for the purpose of sharing pictures or videos of a sexually explicit nature. I'd like to define a rule that goes something like this:

This is a community of professionals. While we recognize that people have sexual elements, we'd like to preserve the ability of our members to avoid that content if desired. Profiles containing sexually explicit language are prohibited, as are egregiously explicit text and media not behind a CW. This is not meant to ban artistic expression, but to provide a safe environment for our users. What is sexually explicit is at the sole discretion of our moderation team."

**Comment by KitKat31337** [comment]
With the expanded visibility of content (that you don't need to specifically follow someone to see them, even on another instance) I believe it is reasonable to require that anything NSFW be behind a nsfw or lewd CW.

**Comment by threddyrex** [comment]
Good idea, thanks for bringing this up.

Additionally, is there a specific CW that should be used? ("_you said it just needed to be a CW, not **what** CW it should be..._")

**Comment by benwis** [comment]
I would say to leave that undefined, at mods discretion. That way we can issue warnings for first time offenders and immediate suspensions for others.

------- Original Message -------

**Comment by benwis** [comment]
> Good idea, thanks for bringing this up.
> 
> Additionally, is there a specific CW that should be used? ("_you said it just needed to be a CW, not **what** CW it should be..._")

Is there a mastodon standard CW for that?

**Comment by CrowderSoup** [comment]
> Is there a mastodon standard CW for that?

@benwis after a few years floating around the space the most common CW's I've seen for sexually explicit content are "LEWD", "Nude", and "NSFW".

**Comment by dominichamon** [comment]
"Profiles containing explicit language are prohibited" does that mean i can't swear in my bio?  it might be good to tighten up the language here and focus on sexually explicit language.

**Comment by fairyambassador** [comment]
I think this is mostly okay, but singling out sexual content alone feels discriminatory. For example, I'd like to see violent content (e.g. some news stories) behind a CW as well. I realize determining what sort of content is objectionable is opening a can of worms, but it feels pretty important to go through the worms in this case. The anti-capitalist in me would like to see an explicit definition rather than relying on "Safe For Work", I don't feel _that_ strongly about the SFW label.

**Comment by Preskton** [comment]
Recommend we rephrase the rule as: "Sexually explicit content must apply a content warning to text & images" to improve overall readability (remove double negative) and clarity.

Also recommend we clarify `explicit language` as this appears to cast a wide net, e.g. if I include the word `shit` in my profile, will I be banned?

**Comment by kwyn** [comment]
I think "moderate discretion" can be tricky as inherent biases come into play. Having a stricter set of criteria of what is and is not allowed is probably wise otherwise enforcement could be inequitable and defining recourse processes for a user being banned or wanrned would be necessary. 

To be clear though I'm definitely for having some sort of guidelines and have those guidelines added to server rules on sign up so those who accept those rules should be expected to hear to a concrete content/behavior standard.

**Comment by nikp** [comment]
@gblues  Sex work is work; So is trauma surgery; Not all nudity is sexual.

Nevertheless, I think there is a reasonable expectation that a "professional" workplace would frown upon any nudity (even artistic non-sexual), and surgical procedure imagery, in a work context.

Given the overall theme across our industry of aggressive layoffs and management choosing to exercise draconian enforcement of corporate policy, such things could even be used to affect someone's employment.

That can be true without raising SWERF concerns. 

I don't see where in https://hachyderm.io/about/more you see that it is labeled as "explicitly NSFW"

I think content warnings would be appropriate, and then every individual user is free to configure their clients to automatically expand or not expand content-warned toots, right?

**Comment by hydratim** [comment]
@gblues Both @jmerritt and yourself raise valid points, and I don't disagree with you. 

However, We can be an NFSW accepting community with CWs. 
Having a requirement for CWs is not shaming, banning, or otherwise demeaning. It's simply blurring of content that people might not want to be seen over their shoulder in the office. Said content can be unblurred at the click of a mouse.

I agree that the text of the rule needs work, as it stands the proposed text is unacceptable, but the concept of requiring a CW is honestly not censorship.

**Comment by krisnova** [comment]
I agree that we need to be careful about the "Pornography: We know it when we see it" mentality because it can be very harmful to sex works. 

Here is what I suggest we change the name of the rule to:

> No off-topic or repetitive sexually charged content.

Basically, I am convinced that none of our rules should ever even mention "content warning". That is a feature of Mastodon and not even in the ActivityPub spec as far as I know. It's an accessibility feature and not a part of the backing service. We just need to give up on the idea of becoming the content warning police.


As far as my rule goes I define it like this:

### Off topic

Seemingly independent posts that have nothing to do with the conversation at hand. If two people are talking about a piece of technology and all of a sudden a dick picture appears I would consider that off-topic. I would want a rule in place to allow us to moderate that.

### Repetitive 

This is similar to the "empathy bots" that continue to send the same message in different words asking for help. While I want to support people, I don't know if we want to allow an account who's only content is off-topic and repetitive sexual media. We see a lot of these accounts show up. We need a rule in place to allow us to moderate this.

### Sexually charged

In 2019 I walked away from 1.4 million dollars in RSUs at VMware because I was getting shit for wearing my leather collar to work. 

I think there is a difference between "I am a professional and have a kink, or sex work is my job" and here I am jamming sexual content in your face for advertising or personal arousal reasons. I don't want people "getting off" on hachyderm. But I also want to make sure we respect that people (like myself) will have sexual parts of their personality and day-jobs that they should feel welcome to bring to hachyderm.

**Comment by jmerritt** [comment]
> but also prevent people's local timeline from having tons of nudity.

Is this happening? I just don't see this happening to someone who doesn't wish to see sexually explicit content. Here is how visibility flows in Mastodon.

![97d44501148458f7e437697eee7be50a-Full](https://user-images.githubusercontent.com/130459/201995695-92eb3ea9-e62e-40de-8fab-66d42d1b5c5f.png)

**Comment by benwis** [comment]
> Is this happening? I just don't see this happening to someone who doesn't wish to see sexually explicit content. Here is how visibility flows in Mastodon.

Yes, we've had at least 3 accounts today that hosted here that post unCWed nude content. So there's your local feed. Each of those received about 10 reports. We've also had some content federated in. So it depends on what people would like in their Local and Federated timelines. The Federated timeline is fairly inevitably going to have some of that, but I'd like the Local one to be better

**Comment by krisnova** [comment]
Basically we need a way to be able to moderate things without also casting people out of our community because we don't understand them.

A lot of people joined hachyderm because of trust, if we can sustain that trust I expect it to go a long way.

---

We definitely don't want to get in the "gauging female presenting nipples" business. Our mods have better things to do than to pass judgement on the gender binary norms of someone's nipples.

**Comment by rossyoung5** [comment]
@krisnova Was pondering if "No off-topic or repetitive ~~sexually charged~~ content" could work (covering some of the 'empathy bot' scenarios) , but that feels way too broad... Those first two definitions seem to be the real crucial parts though.

And to @jmerritt's point: 
> let other rules like those covering harassment and spam do the heavy lifting here 

I didn't see anything in the [community doc](https://github.com/hachyderm/community) or the Server rules about spam or harassment, but I agree, once those rules are in place, dealing with off-topic or repetitive sexually charged content would seem a lot easier to moderate.

**Comment by benwis** [comment]
> @krisnova Was pondering if "No off-topic or repetitive ~sexually charged~ content" could work (covering some of the 'empathy bot' scenarios) , but that feels way too broad... Those first two definitions seem to be the real crucial parts though.
> 
> And to @jmerritt's point:
> 
> > let other rules like those covering harassment and spam do the heavy lifting here
> 
> I didn't see anything in the [community doc](https://github.com/hachyderm/community) or the Server rules about spam or harassment, but I agree, once those rules are in place, dealing with off-topic or repetitive sexually charged content would seem a lot easier to moderate.

Harassment definitely falls under Rule 1. Spam definitely needs some work

**Comment by krisnova** [comment]
Spam needs work. I would love to see a "No spam" issue similar to this one show up today as well to be honest. 

I would like to keep the word "sex" or "sexual" in the rule even though it runs a risk of being leveraged against sex works simply because we see a lot of it and it will be helpful for us to moderate. 

At some point we will need to trust hachyderm and the mods to be good stewards of the community.

What about this for the official rule language:

> No off-topic, repetitive, deliberately disturbing, or extraneous sexual/erotic content.

**Comment by quintessence** [comment]
(Caught up - lots of people made good points that I agree with so I won't rehash a ton, just lending support for "we shouldn't be the content police" and so on. I also want to explicitly say that I don't support what I think is referred to as "respectability politics", the notion that a single body can determine what looking nice, dressing nice, sounding nice, etc. is defined as.)

To answer the latest question:

> If a sex worker had an account here, they'd probably have repetitive sexual content. Or an artist who regularly works with the male/female form.

I don't know if that's true per se. Based on how we're separating engagement between corporate, OSS, and influencer accounts we're basically asking to only promote "work" type things in special account types. That would mean that for a sex worker that wanted to promote their work, they'd need to apply to / fall under one of the special account types, follow the no repetitive posts rule (can't keep re-posting the same content, event, etc.), and all of that. And without all of that they're just a person with an account that has a job like any other job. Putting it another way, they aren't going to be posting the nuance of their work any more than a non-corp / OSS / influencer account would post about their work in different fields.

**Comment by benwis** [comment]
> (Caught up - lots of people made good points that I agree with so I won't rehash a ton, just lending support for "we shouldn't be the content police" and so on. I also want to explicitly say that I don't support what I think is referred to as "respectability politics", the notion that a single body can determine what looking nice, dressing nice, sounding nice, etc. is defined as.)
> 
> To answer the latest question:
> 
> > If a sex worker had an account here, they'd probably have repetitive sexual content. Or an artist who regularly works with the male/female form.
> 
> I don't know if that's true per se. Based on how we're separating engagement between corporate, OSS, and influencer accounts we're basically asking to only promote "work" type things in special account types. That would mean that for a sex worker that wanted to promote their work, they'd need to apply to / fall under one of the special account types, follow the no repetitive posts rule (can't keep re-posting the same content, event, etc.), and all of that. And without all of that they're just a person with an account that has a job like any other job. Putting it another way, they aren't going to be posting the nuance of their work any more than a non-corp / OSS / influencer account would post about their work in different fields.

Interesting! I would consider a SW to be an influencer account more than a corp account, and that they probably would post different images(for example) than the same one over and over.

**Comment by krisnova** [comment]
Locking this issue for now. We will roll out our first attempt at consolidating this as soon as we can.
