### ISSUE TITLE
Hachyderm to be defederated from rage.love

### ISSUE THREAD

**Issue by tehstu** [hachyderm/community#353]
### What domain(s) need to be added or removed from our blocklist?

Apologies if this is not the correct issue to open. The two links in the "please read before processing" give 404 errors and I was hesitant to tag anyone in an actual post. 

I was browsing the Fediblock hashtag and came across this post, where an admin announced their intent to defederate from our community. Honestly, the claim seemed so unlike my experience of Hachyderm that I wanted to draw your attention to it, lest those outside the community draw incorrect conclusions:

https://rage.love/@admin/109985145492344865

Unfortunately, it looks like the "receipts" are in a post only accessible to members.

Again, apologies if this is not the method of reporting this, or if we typically don't take action to these sorts of declarations.

Thanks for reading.

**Comment by quintessence** [comment]
Not a problem and this is a completely ok place to ask this question.

To answer you: on 25 Feb, Nóva made a post that discusses the problematic history of ownership in US law. She has since taken the thread down, so I have attached our record of it, and posted an apology here:

https://hachyderm.io/@nova/109988337092641705

As for defederation: as moderators on the Fediverse we support Rage.Love's decision. One of the strengths of decentralization is that individuals and instances can walk away from each other in this way. Right now Rage.Love does not feel that Federating is in their instance's best interest, so their admins are making the choice to enact that decision.

![Nóva's thread](https://user-images.githubusercontent.com/3387286/223970918-2a9fb3d2-ca29-458d-9e31-3dc38c8ac164.png)

**Comment by tehstu** [comment]
That makes total sense, appreciate the reply! 

Should I go ahead and close the issue?

**Comment by quintessence** [comment]
I'll go ahead and close it since you have what you need! ❤️
