### ISSUE TITLE
Specialized Accounts: Backloggery

### ISSUE THREAD

**Issue by MrDrumble** [hachyderm/community#389]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

Backloggery is a small, Patreon-funded site designed to help users manage their video game backlogs. This account will be used to share the latest site changelog with users, discuss/brainstorm new features and design philosophies, and address issues within our community.

### How will you ensure the community is protected?

We have always strived to run an open, inclusive community and will continue to do so.

No content on this account will be automated.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
👋 Based on review / separate emails, I think that your project most closely fits our OSS Projects as a community type of project, so that's where I'll slate you on the approvals page :) 

Speaking of: you've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.
