### ISSUE TITLE
Specialized Accounts: @codeandsupply

### ISSUE THREAD

**Issue by colindean** [hachyderm/community#393]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

[Code & Supply](https://codeandsupply.co) is a community of software professionals based in Pittsburgh, Pennsylvania but with a nationwide audience and worldwide reach. We love open source software but are not exclusive of non-open source topics. We've held more than 500 meetups, several conferences, and operate a cozy, not-profit-seeking co-working space with meeting space offered for free to free, public, and tech-related events. We have an active chat community with an engaged, active moderation team. We believe in education, inclusion, and ensuring all who want to participate can while they're honoring each others' humanity and the learning process.

### How will you ensure the community is protected?

We expect that our content posted will be relatively benign: event announcements, job postings, and the occasional artsy picture or programming or design problems memes. What we post will likely be similar to what we post on [Twitter](https://twitter.com/codeandsupply) (for however long we keep that around) and [Instagram](https://instagram.com/codeandsupply). Anything we post will certainly abide by the [C&S Conduct Policy](https://codeandsupply.co/policies/conduct) in addition to the Hachyderm equivalent, and take the more strict where there are differences.

### (Accounts with Automated Posting/Bot Accounts Only)
> What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

We'd like to bring our Job Board integration to our Hachyderm account. The post volume is minimal, maybe 2-3 per week but there are sometimes lull-breaking surges of activity in the days before our monthly email newsletter. While these posts are automated, we review each after posting in the normal course of community engagement since the same posts also go in our job board Slack channel where our Conduct Team would see anything bad and take action. 

We've never had a conduct violation via our job board, as posts there are tied to paid and identified accounts on our website. A violation could result in losing job board and other community privileges in perpetuity.

**Comment by quintessence** [comment]
👋 Thank you for submitting this! As an FYI since I saw you used your links for social: since only the links in the "meta" fields can be validated, you might want to put any links you don't plan to validate in your bio and keep those fields for any URLs you do validate (e.g. if you validated one of your social media accounts). This is not a requirement, just a suggestion in case it helps :) 

For the approval: You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by colindean** [comment]
> you might want to put any links you don't plan to validate in your bio and keep those fields for any URLs you do validate

Excellent advice. Done.

> Once this is done it should show as green on your profile. 

![image](https://user-images.githubusercontent.com/197224/233218216-11c5e9c8-1f76-4f21-a168-1dbe9bfa7a12.png)

Thank you!
