### ISSUE TITLE
Consider public, read-only Grafana dashboards

### ISSUE THREAD

**Issue by nkcmr** [hachyderm/community#4]
Hi! 👋 First of all, thank you for running hachyderm.io. It runs very smoothly compared to other instances!

To the point: I've noticed @krisnova posting some screenshots of Grafana dashboards. Maybe there could be a small collection of publicly-accessible dashboards that show critical metrics.

Pros:
- Allows crowd-source issue detection
Cons:
- Might turn into a thing that people nag the admins/mods with? (example: "This dashboard is going up and to the right! That seems bad!", turns out it is fine)

Thanks again!

**Comment by kingdonb** [comment]
I just wanted to chime in and echo that the transparency is awesome, I think I saw the toot you're talking about in the server-wide notification, I was wondering if there's a way to go back and read old notifications that came that way from the instance?

I tooted about it here: https://hachyderm.io/web/@yebyen/109303826183477956

I think public dashboards would be helpful for anyone who is going to wear a pager for Hachyderm, at least I think that those dashboards would be helpful, whether or not they are public. I am in general interested in the observability of Hachyderm and how things are going as a service, and if I'm able to help in any way I'm more than interested.

My experience is with kube-prometheus-stack, for now

I don't know well enough or in any way even where Hachyderm things are deployed for myself to say how they should be monitored or what metrics to expose, at this point, but I'm interested and would be glad to help answer this by spending some volunteer time, or starting up a stream and/or tuning in and listening at a particular time... you know, in order to receive the benefit of the community's instructions, if that's something we'd like or if that type of thing was going to be a thing...

**Comment by dominichamon** [comment]
i would be ok with exposing some of these grafana dashboards as read-only... i have no idea if this is feasible (https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/ suggests it's an alpha opt-in feature).

**Comment by dominichamon** [comment]
starting to figure out which charts we'd want to show.

but statsd export from Mastodon doesn't containing other interesting things like active users, posts per day, etc.  we'd want to pull that from the API and would need a custom prometheus exporter.

maybe, given the interest in mastodon, a prometheus-mastodon-exporter isn't a terrible idea.. it could pull from statsd _and_ the API and power some interesting dashboards.

**Comment by kingdonb** [comment]
The link that was posted in the Announcements board is excellent:
<img width="748" alt="Screenshot 2022-11-10 at 7 44 56 AM" src="https://user-images.githubusercontent.com/3286998/201094962-82202491-9960-467e-900b-cebfed8ad776.png">

These are the metrics that I imagine people will be most interested in. Is it OK to post the dashboard link here itself, or should we wait to publish it until there is a stable URL? (I screencapped it, which should be enough to help us gather feedback and to facilitate the iteration... the URL is a numbered hash though, and I don't want to create bad links in a permanent/public setting in case it won't be stable or permanent... so I haven't linked it here.)

**Comment by dominichamon** [comment]
i think that link is pretty stable (if ugly)

**Comment by nkcmr** [comment]
This issue feels closable to me. Those metrics are great and provide exactly what I was looking for :)

I'll let the mods/admins decide if it should be closed.

**Comment by dominichamon** [comment]
we will keep adding more, but I agree.
