### ISSUE TITLE
How do folks feel about web3 enthusiasts?

### ISSUE THREAD

**Issue by mkeeter** [hachyderm/community#40]
Low-effort shilling of particular tokens seems like it's already covered under "Don't Be a Dick" or the proposed "No Spam" rule (#37).

I'm curious about the grey area: real people, who are just _really into_ web3 stuff.

Because of the tokenomics incentive structure, I feel like these account are **never quite acting in good faith** - they've always got a profit motive of some kind.  This makes me wonder whether such accounts should be held to a different standard, e.g. how Hachyderm is handling [Corporate Accounts](https://github.com/hachyderm/community/blob/main/accounts/corporate-accounts.md).

(My bias would be to encourage web3 enthusiasts to find a different server entirely, but I'm very much of the [Web3 is Going Just Great](https://web3isgoinggreat.com/) school of thought)

**Comment by rossyoung5** [comment]
That def feels like grey area territory. It's one thing if someone's a stakeholder in [insert-word]-coin or shiny-new-NFT-thing and trying to solicit interest, but saying 'someone interested in web3 means they get different rules' seems murky. 

Is there a widely accepted definition of web3 that isn't overly broad? Blockchain implementations are 'out there' at a commercial level, so if an IBM developer working on Hyperledger jumps in are they in the same boat as the cryptobros?

I get the spirit of the request, but if someone's not spamming or being a dick, it feels icky telling them what they can/can't be into.

**Comment by mkeeter** [comment]
Good point – by "_really into_ web3 stuff", I'm also implying "posts about it a lot", since I'm assuming Hachyderm doesn't want to be the hobby police.

e.g. something like [this person's Twitter account](https://twitter.com/nifty_pat)

(one counterargument: is this any different than someone in DevRel that's posting a lot about their company?)

**Comment by rossyoung5** [comment]
I would say as long as it's not breaking other rules, there's no _real_ problem that I can see (for DevRel or web3 peeps). I know there are separate agreements listed out for influencers/corporate accounts. With the distinction being

> We draw the line between "personal brand" and "corporate account"
(https://github.com/hachyderm/community/blob/main/accounts/influencer-accounts.md#self-promotion)

As long as individuals are not acting in a predatory or otherwise rule-breaking manner, I think at some point we have to trust our community to use their brains and decide for themselves to mute/filter/etc. at an account level if they so choose instead of instance-wide.

**Comment by quintessence** [comment]
Going to go ahead and close this with agreement with the stance: you can be really into something, but still need to follow the rules against: spam, fundraising (or signups, whatever term applies), corporate, etc. accounts. Web3 accounts will be handled with the same rules.
