### ISSUE TITLE
Can't follow user from another server

### ISSUE THREAD

**Issue by stumyp** [hachyderm/community#405]
### What would you like to discuss with us or let us know?

I am trying to follow this user and system shows account as suspended.

https://hachyderm.io/@Cloudguy@sackheads.social

![image](https://user-images.githubusercontent.com/5258641/234742966-9b5f29c9-b9c7-4482-a34d-57d75f745ebc.png)

If I go directly on his page I see account as active:

https://sackheads.social/@Cloudguy

![image](https://user-images.githubusercontent.com/5258641/234743008-5f0c911f-481e-45dd-8ba0-7d9e19c870cb.png)

**Comment by quintessence** [comment]
👋 Hello! Head moderator here. The Hachyderm Moderation team actually only discusses policies and clarifications in the public, rather than commenting on individuals who have been specifically moderated. That means I can tell you how we determine if an individual, remote, user is de-federated from:

The Hachyderm Moderation team recognizes that only local users have agreed to the "Don't Be A Dick" policy or other server specific policies. This is why we have rules around bots on our local server, but do not moderate bots by our policy if they're (for example) from botsin.space . We only moderate remote users if they are reported for infringing on the safety of the Hachyderm Community. This can include posts that support TERF ideology, homophobia, anti-Blackness, antisemitism, and so forth. The specific moderation action taken (limit, suspend) depends on a combination of the severity and frequency of the original infraction. This is because the Hachyderm Moderation team recognizes that response to a report is a reactive response: one or more persons would have already seen, and been impacted by, what was reported to even file the report.  ([This latter aspect of the Hachyderm Moderation team structure is in our Moderator Covenant.](https://community.hachyderm.io/docs/moderation/covenant/))

Individual users are welcome to reach out to the Hachyderm Moderation team at admin@hachyderm.io if they would like to discuss individual moderation concerns or what paths can be taken to reverse the decision.

**Comment by stumyp** [comment]
Thank you for detailed reply @quintessence.

I don't think this is critical enough to start a campaign to unblock this specific user. I just wasn't sure what to do in these cases. Your comment gave a very detailed explanation.

(joking) Also I do not see how a person named "Dick Morrell" can agree to a "Don't be a Dick" policy LOL  (/joking)

**Comment by quintessence** [comment]
(joking) Also I do not see how a person named "Dick Morrell" can agree to a "Don't be a Dick" policy LOL (/joking)

😂
