### ISSUE TITLE
Degrees of (de)federation

### ISSUE THREAD

**Issue by erlend-sh** [hachyderm/community#442]
In light of Threads planning to join the fediverse, there’s an ongoing discussion about how to handle federation, if any, with their mega-instance.

Hackyderm statement: https://community.hachyderm.io/blog/2023/07/07/a-minute-from-the-moderators/

What’s challenging for me as a user who’s unfamiliar with the administrative controls of a Mastodon (or similar) instance is that I don’t know the federation options at our disposal.

https://writing.exchange/@erlend/110671771287690551

There are more ways to go about this than a binary ‘do or do not federate’ decision, so I’d love to better understand what different outcomes are up for evaluation here.

So far the approach that sounds most appealing to me is a ‘limited federation’ that only allows me to explicitly opt in to following one Threads account at a time, and letting other Threads accounts *request* to follow me.

https://hachyderm.io/@mjf_pro/110679613430398836

**Comment by tehstu** [comment]
I happened upon this article about Threads vs the future of Mastodon and didn't realize this federation mode was an option:

https://tracks.ranea.org/post/722507935765397504/youre-so-vain-you-probably-think-this-app-is

> Personally, I would federate with Threads in “silence” mode: my instance’s users would be able to follow Threads users and vice versa, but posts from Threads would not show up in any public timelines on my server.

**Comment by hachyderm-admin** [comment]
Hello!

There are various tools that can be used to handle federating, and to what degree. In the Mastodon toolset, as tehstu mentioned, there is the ability to Limit a server. Limiting a server allows users to search for each other, but doesn't allow server posts to show in the Federated Feed. It's especially helpful for bots and the like that make use of the Federated Feed to respond, follow, etc. users of instances federating with the bot's instance.

For completeness: the other main option we can do at the instance level would be "rejecting media". This is mostly useful when we need an instance to mark most / all of their media content as sensitive so it can be opted into. (This wouldn't apply to a non-homogenous situation like Threads, where there's a variety of content, but might apply to an instance that had a singular topical alignment.)

Since we have a separation of duties, determining the above would be handled by the Moderation Team.

Depending on the server traffic, there are also traditional server admin tools that are useful.  This is under the purview of the infrastructure team. This is how the Hachyderm is protected against either accidental or intentional malicious traffic and so on.

In the case of an instance the size of Threads, if Threads federates (instead of Meta keeping to their own ecosystem), then part of the reason we'd need to do analysis on the instance is to figure out what combination of tools would best protect our user base. How many domains are federating and which? Do we need to manage the traffic volume? Do we need to defederate entirely or are we doing social graph research around individual (hate) accounts? Do we need to put additional safeguards in place besides what is directly available in the Mastodon tooling? There's a lengthly list of questions here, and more, and there's a lot that isn't predictable in advance.

That said, the main benefit we see is the conversations around safety and privacy that emerge on the Fediverse for how existing tools and human process can be improved. 

Does this help?

**Comment by michel-slm** [comment]
Hello there!

I'm a Meta employee - I don't work on Threads but on our Linux Userspace team and most of my work is basically open source community contributions.

Just my two cents - I'm considering migrating /to/ Hachyderm from floss.social precisely because they took blocking Threads.net way too far (IMHO) - they also block any known IP address belonging to Meta (not even distinguishing between corporate and production networks), meaning I can't even access my own account from the company's network.

https://floss.social/@michel_slm/110820853348392165

My other instance (that is not as tech oriented, so I don't really want to use it for everything) has a much more nuanced stance similar to what @erlend-sh preferred - the members polled prefer limited federation over defederating or doing nothing - and blocking wholesale apparently was never even discussed (or I missed it)

https://www.loomio.com/d/taD7sGP9/discussion-values-and-priorities-regarding-threads-net/

FWIW as long as Hachyderm won't do IP blocking I'm likely moving here or to Fosstodon (I don't want to take a knee jerk decision)

**Comment by alxndr42** [comment]
There's two things I find concerning about not blocking Threads at the instance level:

One is the well-known tolerance Facebook has for racist/transphobic/etc. accounts and content. My understanding is that I can personally prevent being exposed to these by blocking their domain in my account. But this wouldn't prevent them from accessing my posts via federation, which I also wouldn't want.

The other is feeding the Facebook content monetization (and more recently, "AI" training) machine via federation. My understanding is that as a Hachyderm user, there's no way for me to opt out of that.

**Comment by slamp** [comment]
There is information about Threads in the January blog post: https://community.hachyderm.io/blog/2024/01/14/a-minute-from-the-moderators/

**Comment by dmah42** [comment]
Hello! This post has been closed due to 7 months or more of inactivity. If this situation still needs to be handled, please open a new Issue. Thank you!

Further information on how we're handling Threads will be posted as blog posts by the moderation team.
