### ISSUE TITLE
My follows of users on my relay sever have been removed

### ISSUE THREAD

**Issue by sentience** [hachyderm/community#467]
### What would you like to discuss with us or let us know?

Following restoration of federation with birdsitelive.kevinyank.com in #434, I was following a dozen or so users on that instance. Those follows seem to have been deleted from my account, and attempting to follow them again simply marks them as "pending", but it does not appear that any follow request is sent to the instance. Any change the instance was de-federated again?

My account: @sentience@hachyderm.io
Sample account I was following and am no longer able to follow: @abcnews@birdsitelive.kevinyank.com

Thanks in advance.

**Comment by soupglasses** [comment]
Federation was indeed disabled on `birdsitelive.kevinyank.com` due to the server improperly responding to all delivery attempts 7 days in a row. I have now reinstated the delivery attempts, so you will have 7 days to look at this before mastodon will flag the instance as faulty again. If that occurs, do not hesitate to ping me or by writing a comment on this issue about reinstating delivery attempts once more.

Hope that is of help! :D

**Comment by hachyderm-admin** [comment]
Hello and apologies for the delay!

As a result of the changes with Twitter, a lot of Twitter mirrors were shut down and needed to be defederated from. When we were doing this, we tried to leave 1-2 Twitter mirrors online so that people could still make use of them. There are some notes about this in GitHub Issue #403 .

We took a look at your mirror and based on our notes it looks like it was non-responsive at the time we defederated / had errors queuing up, so it was removed as an unresponsive mirror. We've gone ahead and re-federeated with your Twitter mirror, so you should be able to use it normally again :) 

Please let us know if there are any questions!

**Comment by sentience** [comment]
Thank you! Sounds like I need to set up some uptime monitoring on my mirror. 👍🏻
