### ISSUE TITLE
Enable GitHub sponsors

### ISSUE THREAD

**Issue by itrich** [hachyderm/community#5]
I just migrated to hachyderm.io and really look forward to building a new community here. Thank you for providing this service and maintaining a safe space. :pray: 

Would it be possible to activate GitHub sponsors in order to give some kudos to the ops team of hachyderm.io?

**Comment by april** [comment]
Happy to open this up as a new issue instead, but could we make it more generic and include Patreon as well?

Not a big deal to use ko-fi or the like, simply trying to consolidate the list of places where money leaves my wallet. 😂

**Comment by sandyarmstrong** [comment]
Is there already some blessed way to monetarily support hachyderm?

**Comment by krisnova** [comment]
So I am happy to set up other ways of donating it will just take time. Please follow along as I figure out the future of money and how to manage our new community.

**Comment by itrich** [comment]
> So I am happy to set up other ways of donating it will just take time. Please follow along as I figure out the future of money and how to manage our new community.

Thank you! 🙏 
Don't hesitate to reach out if we/one can contribute to managing the community.

**Comment by olloeco** [comment]
+1 for Patreon or any other voluntary monthly membership platform. @krisnova, I had to poke around a lot to find a way to contribute to you and the project; if you could pin the post that @itrich linked to, that would be helpful! I know that you're not trying to turn this into a giant megaproject or make people feel obligated to contribute, but I know that there are lots of community members who want to support our instance. I've only been here a few days, and I couldn't be happier!

**Comment by jbinto** [comment]
+1. Would love another way to donate other than Ko-Fi. 

My issue isn't with Ko-Fi, if Stripe were enabled, it'd be a done deal. My issue is with _Paypal_. There doesn't seem to be a way to donate even one-time without creating a Paypal account. I'm (begrudgingly) okay to _check out_ with Paypal but I have major (and I think reasonable) trust issues with Paypal and just won't be signing up for an account there.

In the meantime I've subscribed with Twitch, but they take ~50%. 

`:take-my-money-meme:`  ;)

**Comment by krisnova** [comment]
Hello everyone.

I wanted to share a a follow up on this topic. 

The existing ko-fi donation site is a "temporary solution" to accepting donations for the service that was put in place haphazardly due to the unexpected migration from Twitter.

We will be changing the funding model and breaking the funding mechanism out into it's own financial budget starting January 1st 2023 to align with how the US manages taxes. 

For now (this is due to taxes more than anything else) the only way to donate to our service is by leveraging my personal ko-fi donation mechanism and trusting me to put the money toward hachyderm.

In January 2023 we will have a dedicated funding model specifically for Hachyderm, and we intend on supporting many payment platforms as well as building a transparent budget.

In the meantime our neglect to support something other than paypal isn't falling deaf ears, its mostly just dealing with the IRS. 

More on the topic here: https://community.hachyderm.io/blog/2022/12/04/growth-and-sustainability/#donations

**Comment by krisnova** [comment]
Reopening and serving as a placeholder for January 2023.

**Comment by quintessence** [comment]
It took a bit, but these are finally enabled.

The parent org's, Nivenly, sponsor page is up:

https://github.com/sponsors/nivenly

And Hachyderm and Aurae are still pending but will be here when they're ready:

https://github.com/sponsors/hachyderm

https://github.com/sponsors/aurae-runtime

Donating to Nivenly supports Hachyderm ( and Aurae ) . Thank you all for your patience :D
