### ISSUE TITLE
Defederate snarfed.org bridge to Bluesky

### ISSUE THREAD

**Issue by alxndr42** [hachyderm/community#516]
### What domain(s) need to be added or removed from our blocklist?

Someone is working on a [non-consensual bridge to Bluesky](https://snarfed.org/2024-02-12_52106).

Currently known domains related to this project:

- `*.brid.gy`
- `snarfed.org`

**Comment by hachyderm-admin** [comment]
Hello!

Thank you for reporting this. It looks like someone is building the ability to federate with BlueSky's protocol, with the ability for individual users and/or servers to opt-out. Looking at it further, it looks as though the result will be similar to the way federation already works: if your account is public and you aren't blocking an instance on a individual or server level, then it federates.

Can you tell us more about what your concerns are? What we're basically looking to assess here is whether it makes sense to action on the instance as a whole rather than individual users opting out.

**Comment by alxndr42** [comment]
Just like Threads, Bluesky is nothing like "any other instance", and you know it. And just like with Threads, you're hiding behind technicalities, rather than protect your users from known bad actors.

One last thing you could do is to be so honest to remove any claims of being a "Safe Space: LGTBQIA+" (among others), since you're prioritizing playing with cesspools backed by right-wing tech bros now.

This instance has really gone to shit without Nova.

**Comment by hachyderm-admin** [comment]
A lot of people, including Nóva's widow and close friends, are working hard to keep the projects running since her passing. Please bear that in mind when venting your frustrations.

As for the rest: what was asked was for you to voice your specific concerns. Please feel free to do so at a time when you're ready. This can be anything from human to technological. It is important to do this as a user for the same reason there was disagreement about whether Twitter bridges should be allowed or not, and if so which. So far, it clear that you are angry and frustrated but you have not listed out the specific concerns that would be addressed by your request or additional information that would help the moderation team make a determination as to whether or not this is something that requires action on the entire instance (like a block list) or an individual's action.
