### ISSUE TITLE
rel=me usage incorrect on approved account page

### ISSUE THREAD

**Issue by ralexander-phi** [hachyderm/community#534]
### What is your suggestion?

The page: https://community.hachyderm.io/approved/ has rel=me links to multiple unrelated profiles. This creates problems with identity consolidation, as every linked mastodon profile will appear as a single identity.

Instead, a different sub-page could be used for each approved account, allowing each account to verify the link on Mastodon without implying that each account has a shared identity.

References:
* https://microformats.org/wiki/identity-consolidation
* https://chat.indieweb.org/microformats/2024-06-11

**Comment by hachyderm-admin** [comment]
Hello!

The reason the Approved page is not listed elsewhere to is to help prevent some confusion. Only accounts that [Verify with Hachyderm](https://community.hachyderm.io/docs/account-types/verification/) are listed on that page, which is the desired result.

**Comment by hachyderm-admin** [comment]
Hello! We wanted to follow up with this and provide a little extra context and make sure there aren't any additional questions :) 

Since some accounts are required to verify and some are not, the main problem we had to solve was that we needed to find a way that user's could quickly identify if an account that should be verified had done so. This means that the account needed something that we could control that says "yes, they're approved" on an account that they control. 

After some discussion at the time, the avenue with the least user friction and the most user visibility was to use URL verification, a.k.a. the rel=me attribute. This meant that we (Hachyderm) had an asset under our control (the Approved page) that the account holder could link to.

In terms of "is this the right way to use the feature", it kind of depends. Conceptually, this would be similar to associating the identity with, say, a team page on an company / etc.'s page. Multiple individuals might be able to link back to the page that lists them as a team member, but there's one page that lists all of them.


Please let us know if this helps answer the question / suggestion, and if so please close the issue. If not, we're happy to have additional conversation around this :)

**Comment by ralexander-phi** [comment]
Thanks for the extra context. The challenge I'm seeing is that, from the XFN/microformats view, rel=me is supposed to be used for profile equivalence, not membership. I don't think Mastodon supports a mechanism for verifying membership, which is probably why profile equivalence is being (mis)used here.

The rel=me links are intended to be crawled to collect equivalent profiles. Starting on https://github.com I see:

* https://hachyderm.io/@github
* https://community.hachyderm.io/approved/
* https://hachyderm.io/@tailscale
* https://tailscale.com/

Unfortunately, github.com and tailscale.com aren't equivalent profiles as they are unrelated companies. If you made a sub-page like https://community.hachyderm.io/approved/github, that would better match the rel=me semantics.

Google has a good video that shows how rel=me links can be crawled: https://www.youtube.com/watch?v=LabCylbapuM

**Comment by hachyderm-admin** [comment]
Understood. That said, what scenario are you running into that is causing an issue / where are you seeing problems?

**Comment by ralexander-phi** [comment]
I've been collecting RSS feeds by crawling blogroll links (https://github.com/ralexander-phi/rss-blogroll-network), Mastodon pops up a lot because it's popular and every user has a feed. The project has grown to the point where deduplication would be helpful, so I'm looking to turn on XFN/microformats rel=me identity consolidation. The approved account page jumped out to me since it uses rel=me in a way that implies many unrelated accounts share a common owner. Any indieweb crawler that does rel=me identity consolidation would see this issue.

From my end there's an obvious workaround (add the approval page to an "ignore list" since I know it has incorrect information), but I wanted to share with y'all as well.

**Comment by hachyderm-admin** [comment]
Gotcha! We'll discuss internally about doing this moving forward and make a plan to request existing users update if/when we move forward with that. That said you're probably correct that in the short term an "ignore list" will be the quickest solution for your project :) And thank you for bringing it to our attention!

**Comment by hachyderm-admin** [comment]
Since this is something we'd need to start to roll out, rather than something we can just switch (for existing accounts), we're going to go ahead and close this issue for now.
