### ISSUE TITLE
Unsuspend fuckgov.org

### ISSUE THREAD

**Issue by viccie30** [hachyderm/community#546]
### What domain(s) need to be added or removed from our blocklist?

fuckgov.org. It was blocked sometime today, probably for hosting [@fuckgov.org/kamala](https://fuckgov.org/@kamala), an obvious parody account for Kamala Harris. I don't think obvious parody warrants a block.

**Comment by MadokVaur** [comment]
"...an obvious parody account for Kamala Harris. I don't think obvious parody warrants a block."

An "obvious parody account" which has this as its profile statement:

"This account is the official and real account of Kamala Harris, the next President of this great nation. Anyone who disagrees is clearly a paid actor by the Trump campaign. Mastodon asked for Harris. Mastodon received Harris. Mastodon will have Harris. "

"official and real"

Here: https://fuckgov.org/@kamala

More: "Administered by: kamala
Kamala Harris :verified: :verified: :verified:
@kamala"

I see no statement of "parody" anywhere, which, if memory serves, was mandatory on Twitter to avoid blocking in the olden days

In fact it claims to be "the official and real account of Kamala Harris, the next President of this great nation" in so many words

Finally, I've seen at least one post by this account today and it made no mention of 'parody' and was in fact pretty *cough* direct in its language

So. Should Hachyderm block it out right or let individuals fall back on the worn out "just block the site yourself if you don't like it."

Opinions will vary

But it is very clearly *not* a 'parody' account, obvious or otherwise

So how many people will it dupe?

I see some people are aready falling for the sibling "Joe Biden" account, even though it looks like its been moved; apparently there may be some sort of "Nancy Pelosi" profile as well

Let's face it: there's going to be enough dis- and misinformation in this election cycle anyway

Does Hachyderm need to directly support such disinformation?

**Comment by MadokVaur** [comment]
Oh

And checking just now, I see you're not even from the United States

OK then...

**Comment by viccie30** [comment]
I'm not from the US, but that does not mean I can't enjoy at least some parody of the shitshow that is the American presidential election which also occupies a significant part of the news in other countries. 

The content makes it blindingly obvious that it's a parody account, there is zero chance anyone would honestly think that this is the account of a mainstream USAmerican political figure.

**Comment by viccie30** [comment]
Conversely you're not even (primarily) on Hachyderm. Ok then...

**Comment by MadokVaur** [comment]
> Conversely you're not even (primarily) on Hachyderm. Ok then...

No, wrong

I'm on Hachyderm here: https://hachyderm.io/@FinchHaven

And I hope that myself and my entire family will survive the "shit show" that you seem to find so entertaining

**Comment by viccie30** [comment]
I hope that the people Harris intends to kill survive just as well, but regardless of your radical leftist support of Cop in Chief Wannabe Harris, i don't think Hachyderm should block an instance hosting a parody of her. 

I'm sorry you're dealing with the shitshow that is American elections, but I didn't see Dutch people asking for American support when the fascists won here last year. Given the current climate in the USA, I desperately hope for all of you that Harris wins.  All of that still isn't a reason to block a parody of her. 

I did notice your backup account, that's why I wrote "(primarily) on Hachyderm".

**Comment by hachyderm-admin** [comment]
👋 Hello, Hachyderm Mods here. The account was not suspended because it wasn't distinguishable as some sort of parody account. It's that it isn't distinguishable from right wing nonsense, for example:

https://fuckgov.org/@kamala/112853614350041887
https://fuckgov.org/@kamala/112853681925040927

Or punching down on people with mental health issues:

https://fuckgov.org/@kamala/112853495365646784

So the account has been suspended.

**Comment by viccie30** [comment]
Tnanks for the explanation. I don't agree with your/the mods team's decision, but at least the reason is clear. Perhaps it makes sense to also add (a link to) the reason at https://hachyderm.io/about, because for me it still says "Reason not available".

**Comment by hachyderm-admin** [comment]
With rare exception (the Twitter bridges) we don't typically put the reasons with the domains as we obscure the domains on our list. 

People, including instance admins themselves, are welcome to ask about why an instance has been moderated and/or ask us to reverse a decision either via email or here on GitHub.
