### ISSUE TITLE
Unable to login from Mastodon app

### ISSUE THREAD

**Issue by the10thWiz** [hachyderm/community#549]
### Please describe the issue you are seeing.

I'm unable to login with several Mastodon apps.

1. The official Mastodon app (and Moshidon)
2. Husky
3. Tusky
4. Pachli

Most of them report a 404 error. (The others aren't specific). I do not know what route is causing a 404.

### How long have you noticed this issue?

I have only tried logging just now, it worked several months ago when I setup my previous phone.

### What geographic region are you accessing Hachyderm from?

US

**Comment by hachyderm-admin** [comment]
Hello! Apologies for missing this!

Can you send send us an email at admin@hachyderm.io with your username and send the email from the email address you have registered with your account? (This latter is why we're requesting you send an email rather than just posting account information here.)

If that works for you we'll go ahead and close this ticket and switch to email. If you are able to log in and the issue resolved, please let us know and we'll close this ticket. Thank you!

**Comment by the10thWiz** [comment]
Thanks for reaching out. I have determined that I was mistyping the instance URL, and have now successfully logged in. Since I have successfully logged in, I don't think it's necessary to send an email.
