### ISSUE TITLE
Translation service is (partially?) down

### ISSUE THREAD

**Issue by dancergraham** [hachyderm/community#555]
### Please describe the issue you are seeing.

For about the last week I have consistently been getting `The server-wide usage quota for the translation service has been exceeded` messages when pressing the "Translate" link on foreign language toots.  Looking at the server requests this is a 503 Service Unavailable.

```json
{
    "error": "The server-wide usage quota for the translation service has been exceeded."
}
```

### How long have you noticed this issue?

1 week

### What geographic region are you accessing Hachyderm from?

France, Europe

### Is there anything else that we should know?

As a side note I've noticed that the translations have been significantly better recently - I think you switched from Libre Translate to Microsoft or something like that. 
Thank you for Hachyderm - love it !

**Comment by Preskton** [comment]
Howdy, there! This was the first full month we've used DeepL as our translator, and I'd set a "cost control" limit of about $30 USD. I've upped this since it seems our translation service is so popular. Glad to hear that the overall quality has improved, too, @dancergraham!

I just did a test translation after upping the limit, and it worked! I'm going to mark this as closed, but please feel free to re-open if you see something out of place.
