### ISSUE TITLE
Unblock pl.dav1d.xyz

### ISSUE THREAD

**Issue by dav1dxyz** [hachyderm/community#561]
### What would you like to discuss with us or let us know?

Hello, could you please remove pl.dav1d.xyz from your fediblocks? I am unsure of the reason, but it may have been because of the recent anti-black allegations from toot.lgbt, which you can be rest assured I am not anti-black. I just don't like a specific person, and it is not for the color of their skin (which is racism). I do admit the mention was unnecessary, and I have since deleted that post.

I try to be inclusive of everyone, I hope you will unsuspend me. Thanks.

**Comment by hachyderm-admin** [comment]
Hello.

We have received multiple communications from your account in a variety of its forms. Our initial communication included the reason you were suspended, and had to do with your actions and choices rather than an accusation from a third party. Disliking a specific person independent of their race, and engaging in anti-Black behaviors, are separate situations. People are not defederated from for having differences of opinion or disliking specific individuals. People / instances _are_ defederated from by engaging in behaviors that bring harm and/or risk to our community.

Do not continue to use our public facing comms, or private comms / email, to engage in harassment.
