### ISSUE TITLE
Suspension of qoto.org

### ISSUE THREAD

**Issue by Toudahl** [hachyderm/community#57]
Hello,

I am a new user on your server, and of mastodon in general.
As such I wanted to follow the same people on mastodon as I follow on twitter.

Unfortunately, it seems that you have suspended interactions with qoto.org - where Alistair Cockburn has made his new home.

In your suspended server list https://hachyderm.io/about/more#unavailable-content I can see the reason being hate speech.

But according to qoto.org/about/more - they do not allow that.
Could it be that they have improved their rules and moderation to such a degree that the suspension can be reconsidered?

Regards,
Morten

**Comment by untitaker** [comment]
https://mew.toot.cat/mw/Qoto.org

This is the best documentation on this issue that I found, but 1) qoto has burned a lot of goodwill with other instance admins in the past 2) they used a tool with kiwifarms just this week to mass-email admins asking them to unblock qoto 3) they made some weird, non-verifiable claims about what caused the drama that doesn't seem to be generally believed by other users

the entire situation seems messy and like many moderation decisions, this one seems poorly documented as well (not specifically pertaining to hachyderm)

I would vote against this since I don't believe their moderation has significantly changed. It's the same people, the stance on https://qoto.org/about/more seems _very much_ in line with what the toot.cat wiki says (just painted in a more positive light), and I'm not trying to find out what will happen.

**Comment by Toudahl** [comment]
I see. I'm gonna close this issue :-)

**Comment by acjay** [comment]
I'm currently a Qoto user (although I may migrate), and just my  ~2 weeks experience, but it's an extremely chill place with no sign of hate or far right wingedness. Twitter, for example, is a far more hostile space.

Just keep mind that a lot of new users don't have a comprehensive understanding of the inter-instance politics when they join Mastodon and it can produce a really bad experience for new people.

I read the link shared above and while I'm guessing it doesn't capture the entirety of the history, what's written in there seems hardly like a reason to cut off every user on Qoto.

And even if I migrate off, as much as I hear Hackyderm is a great place to be, I don't know if I could choose it, knowing that I'd be cutting myself off from folks on Qoto, who have been nothing but pleasant so far.

This is just my 2 cents, hoping we can be one community, with the exclusion of any instance that abides abuse from their own user base.

**Comment by untitaker** [comment]
Qoto admin has done nothing but escalate the situation of his own defederation over the last days, including calling Eugen (mastodon core dev) a Nazi-enabler by not listing qotos instance on joinmastodon, and publicly thinking about suing the project. While it is possible that his instance no longer hosts hatespeech I think those actions show he cannot be trusted to not overreact if he's just digging himself further in. This network very much builds on trust.

If hachyderm unblocks qoto I'll likely move. Qoto's stance on free speech still does not align with my own views and there is a very good chance hachyderm would isolate itself with that move.

**Comment by acjay** [comment]
That seems like a reason to block him.

But again, the result of defederating the entire instance for regular users (like me) is to essentially be shadow banned from the perspective of Hackyderm's users. I could just join Hackyderm, which I'm considering, except there are totally normal people I've connected with on Qoto who would be shadowbanned from interacting with me and probably not even realize it.

I follow Hackyderm users and see their posts, but I only today realized they can't see me.

I just urge folks on this and other instances to consider the goals and consequences. Defederating Qoto clearly peeves its admin, but it also has collateral damage. And as far as I can see, it does not have any impact on exposure to abuse, assuming the instances that generate the abuse are already defederated (which is good).

**Comment by untitaker** [comment]
I don't think it makes sense to block a harasser but trust that they do a good job of keeping harassers off of their own platform.

it seems people are more actively discussing this at https://github.com/hachyderm/community/issues/73

**Comment by sgryphon** [comment]
Hi, I'm another qoto user, and have been for several years.

I've seen posts that the admin is upset, because the server was a target of attacks (users would set up accounts these, then send abuse, before they could get banned), and then it got removed from the general directory.  No idea how valid it is , but a lot of accusations thrown around , like other admins claiming qoto users have harassed them without action by the admins , but the qoto admin responding that they have no records of every receiving any complaints. (I have no idea which side is incorrect).

I suppose a question is -- how many complaints / abuses have hachyderm ever received about qoto users?  If it is a lot, then I understand the block, although it may make more sense to just silence.  That way all the abuse can't get through, but people who explicitly follow each other can still federate.

The qoto server rules were already posted above, and explicitly ban hate speech (https://qoto.org/about/more)

You can see their public feed here: https://qoto.org/public
