### ISSUE TITLE
Unsuspend brotka.st

### ISSUE THREAD

**Issue by djasa** [hachyderm/community#573]
### What domain(s) need to be added or removed from our blocklist?

I'm considering moving instance to hachyderm.io, thus I was checking if I can follow all the accounts I've been following on the old instance. Finding brotka.st as suspended was a surprise for me, it's a small instance with few users who could be a good fit for hachyderm.io, too (according to occasional boots or threads that I read).

Thus my request: please unsuspend brotka.st instance.

**Comment by hachyderm-admin** [comment]
Hello!

One of the way that we keep our community safe at Hachyderm is to block not only direct offenders ("the worst of the worst", sometimes referred to as Dark Fedi or Alt Fedi), but also block instances that are what we call "friendly federators". This means they are actively engaging with accounts on the Dark/Alt Fedi. The idea here is that even if they are not producing certain types of content, they are engaging with producers of that content.

With all that said, brotka.st is currently on our blocklist due to federating with known Dark/Alt Fedi instances.

**Comment by hachyderm-admin** [comment]
Closing this issue - if there are more questions please let us know!
