### ISSUE TITLE
Specialized Accounts: Nushell

### ISSUE THREAD

**Issue by kubouch** [hachyderm/community#580]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

Nushell is an innovative shell that aims to bridge the gap between a shell and a full-featured programming language. Our account will post mostly technical content, such as release updates, but we encourage also non-technical folks to interact with us since one of our goals is to make shell programming and scripting more human-friendly.

### How will you ensure the community is protected?

Our [code of conduct](https://github.com/nushell/nushell/blob/main/CODE_OF_CONDUCT.md) applies to all our social media accounts and largely overlaps with Hachyderm's rules. We strive to make Nushell a cozy space for anybody and will actively moderate content that violates either ours, or Hachyderm's standards, for example when encountered in comments under our posts.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by hachyderm-admin** [comment]
👋 You've been added to the approval page. We are waiting to push the update live because it looks like your account might not be created yet. Due to how Mastodon verification works, the username needs to already be active and then the verification check runs when the link goes live.


Can you update here with a comment when your account is created and the account handle? Then we'll publish and follow up with next steps.

**Comment by kubouch** [comment]
@hachyderm-admin, I created the account, it is now at https://hachyderm.io/@nushell.

I followed the application process at https://community.hachyderm.io/docs/account-types/verification/ which I understood such that I first need to create the issue before creating the account.

**Comment by hachyderm-admin** [comment]
Thank you for letting us know - we'll make sure to update the doc page!

For next steps: you've been added to the approval page. Please add an `APPROVED` in the links, similar to what [Oxide Computer Company](https://hachyderm.io/@oxidecomputer) has done on their profile. This will turn green with the verification since the Approved link is now live.

**Comment by kubouch** [comment]
Thank you for approving us! Done.
