### ISSUE TITLE
block spam "twitter gateway" domains

### ISSUE THREAD

**Issue by StainlessSteele** [hachyderm/community#63]
Does this server in the fediverse want to let systems like https://birdsite.blazelight.dev/About

**Comment by jakesmolka** [comment]
I think this is as simple at that. Personally, I don't like Twitter content in my feed. But I totally would get it, if someone wants to follow that one account on Twitter, which didn't migrate yet.

Why do you think it is spam?

**Comment by untitaker** [comment]
There are 100s of those sites out there, so everytime I search for a username it's just noise in the search results. Also it really rubs some Twitter users the wrong way when they see their content (artwork in particular) replicated onto random servers. They did not choose to federate

**Comment by jakesmolka** [comment]
Okay, I understand your user perspective. Personally, I wasn't annoyed by it yet.

But blocking domains from our instance won't remove the content from the gateway/bridge servers.

**Comment by StainlessSteele** [comment]
My opinion is that these aren't accounts the users intended to be visible on Mastadon. nor do users really have an easy way to opt out of them. And yes, it's the idea of searching for X user, finding that, adding it and not really seeing their Mastadon content is my concern.

**Comment by wlonkly** [comment]
Adding a bunch more:

* beta.birdsite.live
* birdsite.wilde.cloud
* twtr.vrij.social
* birdsite.tcjc.uk
* birdsite.thorlaksson.com
* beta.mstdn.cf 
* twitterbridge.janis.rocks
* birdsitelive.treffler.cloud

[BirdsiteLIVE](https://github.com/NicolasConstant/BirdsiteLive) is the most common software for it, hence the naming pattern. The author of BirdsiteLIVE [took down his instance](https://write.as/nicolas-constant/closing-the-official-bsl-instance) because of the search problem. [Googling for "birdsitelive" "instance saturation"](https://www.google.com/search?q=%22birdsitelive%22+%22instance+saturation%22&) finds a lot more... can you defederate based on the software the instance is running?

(`botsin.space` has some crossposting bots, but also has original-content bots so I'd be inclined to leave it out of consideration.)

My first reaction to this was "eh, it's annoying but some people might like it", but seeing the volume of BirdsiteLIVE instances and the number of misleading search results, plus @StainlessSteele's comment

> these aren't accounts the users intended to be visible on Mastadon

completely flipped my opinion on it -- those servers don't have the right to republish those tweets, and the volume of false positives when searching for people is high and getting worse.

**Comment by StainlessSteele** [comment]
If Twitter users had to opt into one of those to let them choose for it to be their bridge into a Mastadon instance, or all of them, that's one thing, but this seems the other way around hence I don't like it.

**Comment by wlonkly** [comment]
Nobody had dropped a screenshot in here yet and I think it really speaks to the problem -- I just ran into this again so I took one. Spot the real Martin Fowler, especially as someone new to Mastodon.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/1545955/202936051-348e3834-9fa2-4117-91d9-56bf4b2195e4.png">

**Comment by StainlessSteele** [comment]
Tha5t's exactly it. Why? Which one do I as someone who wants to follow Martin use?

**Comment by wlonkly** [comment]
Damn, this is a _plague_. Here's a bunch more, courtesy mastodon.social's current blocks. (I'd asked a geo-local admin where he'd got his list of birdsites, and he'd copied it manually from m.s.)

```
beta.birdsite.live
beta.mstdn.cf
birb.elfenban.de
birdbots.leptonics.com
birdbridge.autonomy.earth
bird.evilcyberhacker.net
bird.froth.zone
bird.istheguy.com
bird.r669.live
birdsite.b93.dece.space
birdsite.cloutier.co
birdsite.darkesttimeline.social
birdsite.frog.fashion
birdsite.gabeappleton.me
birdsite.gred.al
birdsite.james.moody.name
birdsite.jemverse.xyz
birdsite.link
birdsitelive.bubbletea.dev
birdsitelive.loca.lt
birdsitelive.moistgarbage.info
birdsitelive.treffler.cloud
birdsite.mastodon.me.uk
birdsite.monster
birdsite.nytpu.com
birdsite.oliviaappleton.com
birdsite.skye.cx
birdsite.slashdev.space
birdsite.spectreos.de
birdsite.tcjc.uk
birdsite.thorlaksson.com
birdsite.toot.si
birdsite.vrparty.social
birdsite.wilde.cloud
bridge.birb.space
twitiverse.com
twitter.1d4.us
twitter.activitypub.actor
twtr.carnivore.social
twtr.plus
twtr.vrij.social
twtr.wappie.land
```

These are in _some_ blocklist as "Third-party bots", if we consider to use a third-party blocklist. I haven't looked to see which yet.

And hah, while I was sampling that list for accuracy, I caught this on twtr.plus: 

> [we] only approve accounts where the owner has no reason to believe their Tweets aren't being archived

which is a very creative false negative :)

(@quintessence is the defederation list your jam now?)

**Comment by scambier** [comment]
Ooooh those sites might explain the recent abnormal spikes in users/instances!

![image](https://user-images.githubusercontent.com/3216752/203338105-73c5d145-8562-4f0b-8103-5d4f619e8cc4.png)

**Comment by piccolbo** [comment]
I understand the complaints here. I had the same problem of figuring out which account was the real one for a public figure I wanted to follow. The answer was none of them, they were all bots. And here's the rub. Until the intelligentsia wakes up, this gateway sites are the only way to follow these public figures and stay away from twitter, which is now completely trollified, particularly in proximity of said public figures. It reduces the switching costs for people transitioning to mastodon. I personally follow a few. On top of my mind, Facebook used the same type of accounts to siphon attention out of myspace. But I understand at some point too much is too much. There are some unintended consequences to federation one of which will be a continuous proliferation of accounts and servers from the friendly to the annoying to the trolling. This type discussed here could be useful, if there weren't so many of them. But if you cut out all of them, you may help twitter maintain its silo. And, by the way, nobody stops anyone from creating yet another fake Martin Fowler account, even on hachyderm. The last time I checked there weren't specific rules against impersonation. Perhaps the best way to follow Martin Fowler isn't search, it's going to martinfowler.com and follow a link, because we don't have authenticated accounts on mastodon, as twitter used to. One more thing, the Mastodon Server Covenant encourages admins not to defederate unless necessary: 

> Mastodon is a decentralized social network and we are interested in promoting decentralization. While we respect the use cases of running Mastodon without federation in academic and private contexts, users arriving through our page should be able to participate in the Mastodon network without excessive limitations.

Imagine if your email provider blocked all mass mail because it's spammy.

**Comment by wlonkly** [comment]
Mastodon absolutely does have account verification. Here's Martin Fowler's:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/1545955/204624305-edd77e88-f634-4006-85eb-1d40572eedde.png">

If a public figure chooses not to be on Mastodon, why wouldn't we respect that?

**Comment by piccolbo** [comment]
Sure, if by verification you mean owning a DNS entry, I am verified too. But it doesn't take much to register martin-fowler.io or some such and repeat the same process. I thought that would have been a bit tougher on Twitter in the old days, but I am not privy to the details of the process so I am not sure. I imagine something involving credit cards or licenses or passports. I wouldn't know how to get a Martin Fowler license, even if I suppose the bad guys could. I don't have a good answer to your final question. Maybe since it's not forbidden, and it helps the transition, why not? Because the incumbents have always played hardball with walled gardens and raising switching costs and it's time for payback? Because if Fowler is against having his public content enrich a federated network vs one deranged billionaire he sure can speak up by himself? Not sure I convinced you, but if we start blocking domains because of any number of reasons that have no overlap with our community guidelines, I will have to move elsewhere. I understand coalescing around fundamental norms of respect and tolerance, but when people want to curate my feed for me, that's one step too far for me.

**Comment by quintessence** [comment]
👋 Mod here 

Looks like 1 ) there's a lot of good information in the thread and 2 ) we're getting off topic here at the end. We have an issue we're tracking internally about the Twitter gateway domains both the ones in here specifically and the topic in general. Since we have this one, I'm going to go ahead and close it.
