### ISSUE TITLE
Add hachyderm to Keybase identities

### ISSUE THREAD

**Issue by krisnova** [hachyderm/community#7]
We need to add hachyderm.io to the list of well-known identities that can be verified with Keybase. 

Can someone please [read the docs on how to add an identity](https://book.keybase.io/guides/proof-integration-guide) and help us set up hachyderm on keybase?

**Comment by ThisIsMissEm** [comment]
I think this might be the important part:
> Mastodon has built-in support for Keybase proofs starting with version 2.8.0. Many instances are in listed in the Keybase app but we have paused adding new instances for now. If you are looking to prove your identity on a personal instance then an https proof of the domain should do the trick, proving that you own that instance.

That is, it seems like it's not possible (I'm actually surprised keybase is still a thing)

**Comment by davidshq** [comment]
- [Conversation on Hachyderm](https://hachyderm.io/web/@nova/109302720214352213): 
  - @ramsey@phpc.social: 
    - [Mastodon removed Keybase verification once Zoom acquired](https://github.com/mastodon/mastodon/pull/17045)
    - [Documentation on link verification](https://docs.joinmastodon.org/user/profile/)
  - @Moke: Keybase paused Mastodon verifications on their end.
  - @danieleme@floss.social: [Suggests Keyoxide as alternative](https://docs.keyoxide.org/).

From ["Setting up your profile"](https://docs.joinmastodon.org/user/profile/):

"Because Mastodon can be self-hosted, there is no better way to verify your identity than to host Mastodon on your own domain, which people already trust."

(Doesn't account for when it's a new domain)

Does that mean that this issue is no longer applicable? Is there a specific benefit to be derived from being listed Keybase we should still be looking for in some other service?

**Comment by krisnova** [comment]
Sounds like we are giving up on keybase then?

**Comment by davidshq** [comment]
Unfortunately, giving up on Keybase sounds like the best option atm.

**Comment by Moke** [comment]
@davidshq Why did you tag me in this?

**Comment by davidshq** [comment]
@Moke - my bad, I was attempting to include the mastodon handles of the users who provided info for context, I'll remove the tag.

**Comment by jakesmolka** [comment]
I'm not sure what the original intention of Nova was. But do you all know https://keyoxide.org?
I never used it personally, but I'm seeing it regularly on the fediverse. It appears to have Mastodon backed in already (https://docs.keyoxide.org/service-providers/mastodon/).

**Comment by himbolion** [comment]
Sorry for barging in, but the Keybase integration has been removed on Nov 26, 2021, with [mastodon#17045](https://github.com/mastodon/mastodon/pull/17045).

**Comment by cawrites** [comment]
"Many instances are in listed in the Keybase app but **we have paused adding new instances for now.** If you are looking to prove your identity on a personal instance then an https proof of the domain should do the trick, proving that you own that instance." -https://book.keybase.io/guides/proof-integration-guide

**Comment by quintessence** [comment]
Going to close this one :)

**Comment by quintessence** [comment]
To be clear: we can open up new tickets for KeyOxide et al, it's just that the conversation on KeyBase is decided (it's d/c).

**Comment by doodlemania2** [comment]
If yall learn how to integrate with KeyOxide, that'd be a great writeup - I tried on my own instance for over 3 days and couldn't figure out how to get it to actually work :(

**Comment by quintessence** [comment]
Sure thing!
