### ISSUE TITLE
Unable to create account alias to qoto.org account

### ISSUE THREAD

**Issue by bolapara** [hachyderm/community#73]
I'm trying to move to hachyderm from qoto.org.  When I attempt to create an alias on my hachyderm account I get an error "could not be found" for my profile bolapara@qoto.org.  Is this because the qoto.org instance is blocked?  How do I get around this if so?

**Comment by bolapara** [comment]
Found a similar (old) report here: mastodon/mastodon#12883.  Seems they worked around it by temporarily unblocking the instance so the transfer could happen.

**Comment by bolapara** [comment]
I re-tried after the upgrade to v4.0.2 but still experience the same issue.

**Comment by lyle** [comment]
I have the same issue migrating away from lyle@qoto.org. 
Hachyderm better fits my ethics.

**Comment by dmah42** [comment]
if i understand correctly, as we have suspended federation with qoto.org, you aren't able to transfer your account across.  the solution would be to open up federation long enough for you to transfer.

another solution would be to forego your old account at qoto.org and have a fresh start on hachyderm.io without doing the transfer.

i'll leave it to @quintessence to decide how we want to do this.  my personal preference is to not open up federation with an instance we've previously decided to suspend, even for a short while, but perhaps as we intend to suspend again it will be relatively safe.

**Comment by lambda** [comment]
Would it make sense to switch qoto to limit (silence) rather than suspend, for some fixed period of time (3 months or something, conditional on abuse not getting out of hand), in order to allow users to migrate? I haven't been involved in moderation, so I don't know if the abuse from qoto is so high as to be unmanageable, but limiting the site and suspending individual accounts on it would seem to be a good option allowing a smoother migration process.

**Comment by untitaker** [comment]
I think de-listing for 3 months makes sense. It should probably be much less than that though. See #57. I don't think qoto or their admin is trustworthy. It rather seems they make active efforts to escalate the situation.

**Comment by quintessence** [comment]
Wanted to ping and say I saw this / @dmah42 's mention - lemme think on it.

**Comment by sgryphon** [comment]
I commented on a closed version of this issue: https://github.com/hachyderm/community/issues/57

I have an account on qoto, and would likewise prefer silence over outright ban, so that I can interact with several peeps I know who set up accounts here.

I don't see any abuse on the server (e.g. public feed) itself, but if there is significant abuse being received from qoto users, and the qoto admin is not taking action (hate speech is banned in their server terms), then I understand the ban.

(And if this is true, i.e. the qoto admin is not banning users when notified about breaches, when they have claimed otherwise, then I would like to know that, so I can reconsider having my account on their server).

**Comment by piccolbo** [comment]
For what is worth, I haven't even read it. Your characterization of my position as anti-moderation is completely inaccurate. Associating me with people you  don't like doesn't qualify a reasoned argument against my proposal.

**Comment by untitaker** [comment]
Your position on federation is identical to UFOI principles. That is why I am associating you with them. Neither QOTO nor UFOI would describe themselves as anti-moderation. Others do, in particular because of their experience with how QOTO laid out their principles in practice.

I'm not trying to debate you. The thread, to me, is still about QOTO and I'm adding additional information that IMO shows they should not be trusted.

**Comment by ambihelical** [comment]
Honest question because I really don't understand. Can someone explain to me why it matters to hachyderm admins (and users I guess) which instances qoto.org federates with?  If they are blocking instances they don't like already, why does it matter to hachydermians? They won't see anything from those instances, as far as I understand it.

**Comment by sgryphon** [comment]
> They won't see anything from those instances, as far as I understand it.

Correct. If hachyderm blocks site X, and Qoto does not, it makes no difference. Hachyderm still won't see any boosts, mentions, etc relate to site X.

Qoto could still in theory see messages from X (but in practice, as a Qoto user, the actual feed is clean, as those sorts of messages just aren't common). They could also cut and paste to repeat (and Qoto has a non-standard 'quote toot' feature that helps this), although this more counts as bad content and could be done irrespective of federation status (e.g.someone on Hachyderm could also cut and paste from the public timeline of a block instance, etc)

> Can someone explain to me why it matters to hachyderm admins (and users I guess) which instances qoto.org federates with?

There may be several reasons:
* Actual poor content from Qoto users, especially if reported to Qoto admin and they don't do anything about it. (I think this is minimal, but if it really is a problem then I'll accept that)
* Procedural shortcut / mistaken blocking. Humans use lots of tools to simplify things; Hachyderm admins are volunteers and only have so much time. It may not be feasibly possible to investigate and check every site they hear is a bad actor. So, they use trust that if others have said it is bad, it probably  is, and pre-emptively block it. Very often such shortcuts are valid, and humans could not operate without them.
* Mistaken technical understanding of blocking, maybe thinking that if Qoto boosts posts from a blocked server then Hachyderm would see them. (Not correct, and besides in practice I don't see those types of posts in the Qoto federated feed anyway)
* Philosophical disagreement with the policy of more open federation, making a statement to the admins of Qoto to apply political pressure to try and change their policies. Blocking all the users of Qoto, even with no content, could make those users complain to Qoto admin. It could also make users leave Qoto to a third party instance (because Hachyderm is blocked). Not that this also causes difficulty for Hachyderm users (so inflicting self-harm as well), as the same applies to them: Hachyderm users might complain to Hachyderm admin, or might leave for a third party instance that can access both.
* Personal dislike of the Qoto admin. e.g. the main owner posted an article about the removal of Qoto from the join mastodon directory, that was accusatory against the main Mastodon dev. They also have neo-pronouns on their bio that appear to be mocking (although they have claimed they are not). Humans are emotional, so sometimes the reaction might be to block the entire instance, e.g. if you like the Mastodon devs don't like the personal attacks in article (I would be upset if someone personally attacked me or a friend). Similar to philosophical disagreement, but more for punishment than change. It has the same collateral damage to all the users of Qoto and Hachyderm, preventing them from contacting each other, e.g. they may move to third party servers.

**Comment by ambihelical** [comment]
@sgryphon Thanks for confirming my understanding of how federation works.  You mentioned several reasons why qoto might have been blocked, but that's not really my question, as the reason is listed in hachyderm's list of blocked servers: 'Federating hate speech in the name of "free speech"'.   Qoto clearly federates with instances that have hate speech on them, so I understand the what the statement means (unless I'm mistaken, feel free to correct me), just not why it matters to admins at hachyderm.io.

**Comment by sgryphon** [comment]
>  my question

Sorry; reasons 1 & 2 don't answer your question. Reason 3, 4, and 5 are possible reasons why who Qoto federates with matter to Hachyderm admins (mistaken understanding, political pressure, or one aspect of dislike).

> clearly federates with instances that have hate speech on them

In a technical sense, yes; because federation is generally opt out (i.e. explicit block) and is by default on. The same with all my email providers, they "federate" with email providers that allow hate speech. Not that I ever receive any.

In a technical sense it's not so much that they federate, but that their policy is once brought to their attention they generally do not block the entire server. (Technically Hachyderm also federates with (currently unknown) instances with hate speech, until they learn about it/get complaints about it and then block.)

Qoto does still strongly support individuals blocking servers or other accounts if they want (and has rules about not getting around such blocks), and does not allow any hate speech in their own rules, so in practice being open to receive messages from those serves doesn't necessarily mean you actually will (like my email provider is open).

**Comment by dmah42** [comment]
based on the above discussion we have decided to replace the Suspend for qoto.org with a Silence.  please stay tuned for a future article on the implications of different domain block types.
