### ISSUE TITLE
Help migrate the last 1000 over from mastodon.social

### ISSUE THREAD

**Issue by shanselman** [hachyderm/community#74]
Thanks for such a warm welcome! Things have gone very smoothly. 

When you get a chance, can you kick the follower migration process off again, there's a 1000 lingering followers over on https://mastodon.social/@shanselman that may have been missed in the rate limiting. 

Thank you!

**Comment by krisnova** [comment]
Is this still outstanding?

**Comment by shanselman** [comment]
Yes there’s still 900+ over there.

**Comment by shanselman** [comment]
Looks like 858 folks are stuck on https://mastodon.social/@shanselman @krisnova

**Comment by quintessence** [comment]
Apologies for the long delay - the infra migration last week took all our spoons. I wanted to check in and see if it's still outstanding so we can look into it or if the migration resolved this?

**Comment by shanselman** [comment]
There's still 800+ folks stuck over here https://mastodon.social/@shanselman but it feels like they are mostly on .online? Is that a process that you can click "Retry" on, or should I email their admins (not sure, as that would be a THIRD unrelated mastodon instance, so that feels wrong) @quintessence

**Comment by krisnova** [comment]
So we believe the problem is with the negotiation on how external instances need to re-neogitate the HTTP signatures and public/private keys with hachyderm. In other words, the problem lives on the remote servers such as `qoto.org` and `mastodon.online`. 

Here is the best resource to date that we can send to the remote servers to ask them to renegotiate on their end. https://github.com/mastodon/mastodon/issues/21442#issuecomment-1327954053

They will need to write some Ruby code and a run a job on their instances. Another alternative would be to log back into your `masotodn.social` account and "undo" the redirect to hachyderm.

Send a post asking your followers there to move to hachyderm manually. That is the quickest way to renegotiate between the two instances.

I wish I had a better answer for you as there isn't much more we can do on the hachyderm side short of contributing a Ruby feature to `tootctl` to kick this off manually so at least it's easier for other instance operators to do.

**Comment by krisnova** [comment]
Here you go @shanselman just because I love you: https://github.com/mastodon/mastodon/issues/22281

**Comment by krisnova** [comment]
@ClearlyClaire you can see the abandoned followers here: https://mastodon.social/@shanselman

My observation after looking at our database is that the work needs to be re-sent from `masotodon.social` over to the respective remote servers to renegotiate with `hachyderm.io`.

In scott's case it looks like there are only 2 or 3 servers that seem to have missed the message to migrate followers.

**Comment by ClearlyClaire** [comment]
Yes, I believe that would unstuck existing followers, though I'm trying to pinpoint what happened in the first place.

I have two theories:
- because of load, the server of the stuck followers failed to fetch the new actor in a timely fashion (this is retried 8 times in a little over an hour total).
 In that case, none of the followers from the affected servers would be migrated.
 This could be mitigated in the future by extending the number of retries and adding jitter so not all servers try to fetch the actor at the same time
- another theory I have, at least for `mastodon.online`, is that the `pull` queue has manually been purged because of its size, which would have caused all unprocessed jobs responsible for migrating individual follows to be lost. I know at least `mastodon.social` did that a few times when under huge load in early November at least.
 In that case, this may have resulted in either no followers from the affected servers migrating, or some followers from the affected servers migrating and some not migrating. This is the only case I can think of where some followers on a particular server would be migrated and some wouldn't (while still following the original account), hence my earlier question to @shanselman.
 This is something we can't do much about since it's not the result of a bug, but a manual operation that has caused data loss.

**Comment by shanselman** [comment]
Thanks everyone, this is fascinating. It appears some of them made it but most did not. I don’t have enough info to determine if this is just bad luck/timing/perfect storm, but my spidey sense agrees with Kris’s analysis. I have no way to determine if my timing lines up with manual purges - but if it does then I’m not alone and .online could fix this kicking off a new job right? Plus their manual purge doesn’t explain the other few servers that didn’t get the message so this feels like a valid bug. I wish I could help more but I just did a regular ol’ migration.

**Comment by ClearlyClaire** [comment]
> but if it does then I’m not alone and .online could fix this kicking off a new job right?

No, they would have lost the info, with the server not knowing there is an ongoing migration (that is only recorded as queued jobs, it's otherwise indistinguishable from a redirect without follower migration).

> Plus their manual purge doesn’t explain the other few servers that didn’t get the message so this feels like a valid bug. I wish I could help more but I just did a regular ol’ migration.

Right. It could be a similar issue, or servers failing to communicate in time because of load.

**Comment by ElanHasson** [comment]
I have 7 stuck followers from https://mastodon.social/@elanhasson, should I create a new issue for mine, or is this one ok as it's also stuck on mastodon.social?

**Comment by shanselman** [comment]
Thanks @ClearlyClaire. Last question, and thanks for your patience. Per @krisnova’s suggestion that I cancel my redirect, should I that and then wait a bit and migrate again? (Is that even a thing?)

**Comment by ClearlyClaire** [comment]
> I have 7 stuck followers from https://mastodon.social/@elanhasson, should I create a new issue for mine, or is this one ok as it's also stuck on mastodon.social?

Can't talk for Hachyderm people, but that seems like the same issue, and not something Hachyderm can do much about.

> Thanks @ClearlyClaire. Last question, and thanks for your patience. Per @krisnova’s suggestion that I cancel my redirect, should I that and then wait a bit and migrate again? (Is that even a thing?)

You can indeed re-trigger a migration, and that would likely fix the issue! However, please mind that there is a 30 days delay in Mastodon during which you can't trigger a migration again.

**Comment by ElanHasson** [comment]
Thanks @ClearlyClaire, yah I'll wait until I can trigger another migration. If I still have issues I'll reach out to the admin there.

**Comment by Preskton** [comment]
Howdy, howdy, folks - Hachy Infra person here, following up on older issues. What's outstanding or where can we help, or are we good to close out this issue?

**Comment by shanselman** [comment]
Not sure. There's still 825 folks over there on mastodon.social, but I guess it's they who has to run the script, not us? So if you're cleaning up, I guess it's cool.
