### ISSUE TITLE
Outage page when hachyderm.io is down for maintenance

### ISSUE THREAD

**Issue by ryanmichaelsmith** [hachyderm/community#78]
This would be an effective (additional) way to communicate that the instance is expected to be down. Alot of us were watching the Twitch stream, but not everyone will be that involved and may have missed the prior notifications.

Thanks for the hard work on the 4.0.2 upgrade!

**Comment by StainlessSteele** [comment]
status.hachyderm.io was there the whole time.

**Comment by ryanmichaelsmith** [comment]
> status.hachyderm.io was there the whole time.

And that's fine, but it might be nice to have an outage page.

**Comment by alexbbrown** [comment]
The status page on 2022/11/7 does not mention any of the recent issues that were visible on the notifications view (which sadly requires you to be logged in).

**Comment by sindarina** [comment]
The status page does have status updates, and could therefore be used for such announcements, but aside from the upgrade to 4.x last week it hasn't been used as such. It also looks like whatever monitoring it does takes quite a while to catch up with the actual user experience.

Right now I am getting a default 502 from an nginx frontend, for example, and even the Grafana dashboard is down, while the status page is happily claiming that all systems are operational.

And there has been no update from the team that anyone can read right now, for any of the issues that occurred this weekend, because nobody can read the built-in announcements feed.

Please use the status updates as well? Not everybody has time to check in on Twitch or wherever to see if this is unscheduled downtime, or because someone pulled the plug on stream?

**Comment by sindarina** [comment]
Now the status page says 'Down' while it seems to be back again after a reboot of 'alice'? And now that I can get to the web interface I can finally see that an outage was announced there, where there is no timestamp whatsoever.

![Screenshot 2022-11-28 at 02 13 13](https://user-images.githubusercontent.com/6074566/204171806-2242f12f-4bf2-4fb7-8fb9-275c37c3a4ec.png)

Please announce these things via the status page as well. Thanks!

**Comment by sindarina** [comment]
![Screenshot 2022-11-29 at 10 48 23](https://user-images.githubusercontent.com/6074566/204496176-fc37a58e-95c1-423e-a543-77e54b4e6047.png)

Again, please use your own status page? I know that you are all working hard and whatnot, but I have no way of knowing when this was posted, if any progress has been made since then, etc. It could be an hour ago, it could be 12 hours ago, and reading it requires the instance to be accessible, which makes it a really bad tool to depend on during outages, intermittent issues, and so forth.

It's kind of communication 101 for SRE type work? Have a single, external place where any user can ascertain the health of the system, clearly timestamped, with progress reports, instead of having them piece together their own view from multiple sources, some of which might not be available?
