### ISSUE TITLE
Unable to import Mastodon users as following

### ISSUE THREAD

**Issue by sumitb** [hachyderm/community#8]
Mastodon servers settings have an import page, where you can upload text to follow peeps
Affected url https://hachyderm.io/settings/import

Attached screenshots:

**Comment by jakesmolka** [comment]
Hey, your issue seems to be incomplete. Were you trying to import a CSV of Twitter accounts to follow? That's not what this function is for. It is meant to import Mastodon accounts to follow (see https://docs.joinmastodon.org/user/moving/).
Even though there are bridging tools out there it is not possible to directly follow Twitter accounts from within Mastodon / the fediverse.

**Comment by sumitb** [comment]
@jakesmolka you're right. I worded the issue wrongly, I've edited it now.

**Comment by sumitb** [comment]
The functionality existed, and it worked eventually. There was a delay due to high load on the queues.
