### ISSUE TITLE
Growth goals, capped signups?

### ISSUE THREAD

**Issue by sindarina** [hachyderm/community#92]
I am curious; is a cap on the number of signups being considered, or is 'unlimited' growth the goal? Asking because 'unlimited' seems like it runs counter to what the Fediverse should be, to most people, and because the challenges associated with moderation inevitably mushroom with size. Also, because our fearless leader for life is burning out right now.

So what's the general policy/goal for Hachyderm as a community? What is big enough, when does it get too big?

**Comment by sindarina** [comment]
Having just read [the Medium post](https://medium.com/@kris-nova/experimenting-with-federation-and-migrating-accounts-eae61a688c3c), I can't help but wonder if there is too much focus on growth, experimentation, and fun technical stuff, which could lead to community and long-term sustainability being on the losing side.

I am not particularly thrilled about being part of someone's technical experiment, to be quite honest. When is it enough? What happens when our fearless leader gets bored, or frustrated because too much time has to be spent on the boring stuff, like community management, stability, and so forth?

25.000 users is a small city. They have needs, expectations. Right now it feels like, although you're doing great on the technical side, you're underestimating the rest of it?

And that's before we get to questions around backups, disaster recovery, and so forth. How long is it going to take to bring Hachyderm back up if catastrophic failure were to happen? Like, say, a fire in your basement?

I would very much appreciate having an overview of your goals, in that regard. Which assumptions lead to the projections you mention in the Medium post?

**Comment by ianbattersby** [comment]
> I am not particularly thrilled about being part of someone's technical experiment, to be quite honest.

Conversely, this is what attracted me to this instance. The perceived synergy between my own inner nerd and the amazing efforts by Kris and team is what caused me to sign up.

I think your original point about caps and signups is a good one - if only for the sanity of the team. However, I might suggest those who can't enjoy the technical ride of these early exploration and innovation phases (associated with a homegrown effort) haven't found the Mastodon home that best suits them.

Hope I'm not speaking out of turn @krisnova and @quintessence  🤞

**Comment by alexbbrown** [comment]
kris notes: https://hachyderm.io/@nova/109422128738009473

**Comment by untitaker** [comment]
>However, I might suggest those who can't enjoy the technical ride of these early exploration and innovation phases (associated with a homegrown effort) haven't found the Mastodon home that best suits them.

I strongly reject that idea. Hachyderm might be young but depending on what instance size one prefers, its "early stage" of growth ended already. You can be technically interested without being obsessed with scale at all cost. I'm not saying hachyderm's admins are. They seem to be talking about hacking capitalism all the time.

>kris notes

The concern is that technical growth outpaces social growth, and I don't think this makes me sleep better. So far hachyderm admins have mostly publicly talked about technical challenges, not social ones.

**Comment by sindarina** [comment]
So here we are, almost a week later, running into the scaling issues I was worried about, asked to be patient because "we're working very hard to solve this", signups still not closed, even that would have been a great way to make sure that the problem is at least not getting worse. And the communication about it isn't really improving, either.

These are basic process and procedure problems that can't be solved by throwing more tech at it, or burning the midnight oil. It's a matter of planning, of setting yourself reasonable limits to avoid impacting your users.

If you're too busy, put someone else on crisis communication, or something? It's not rocket science, this 😕

**Comment by sindarina** [comment]
Also, do I really need to point out how silly it is to expect everyone to use this issue tracker for reporting issues, when barely any communication from the team shows up here, and when it does, it's usually another user linking back to a Mastodon post? Use your own tools, document problems when they happen, progress as it happens, both as a record for yourself as well as for the rest of us to read?

I'm sure there will be another bro along in a minute to tell me I should just be grateful or move elsewhere, though 🤪

**Comment by superchromix** [comment]
Fully agree with the OP.  Yes, it's easy to say in hindsight, but unlimited growth was always going to lead to this outcome.  For the past two days the hachyderm.io server has been unstable, and this renders the entire mastodon service basically unusable for everyone who chose hachyderm.io as their home instance.  

Furthermore, it is not trivial to move your account to a new server, because you lose your entire post history when you do this.

Yes, it's a project whose leaders are putting work and dollars into with little return.  Clearly, this is much appreciated by the community.  However, more caution and less growth would result in a better experience for everyone.

**Comment by quintessence** [comment]
👋 Mod here. A few things.

* We appreciate the feedback on our current server policies. It's important to remember that Hachyderm is a free instance, and the admin team is comprised 100% of volunteers. While we strive to provide the best experience possible, and communicate as clearly as we can, it isn't realistic to expect the same uptime and guarantees as a large tech company. If that is the expectation, it's best to look for an instance that matches that for now.
* The list of our current moderators and admin team are public, and can be found [on the mods page in this repo](https://github.com/hachyderm/community/tree/main/mods). If you are on discord, they are helpfully labeled with emoji and colored names. If you have suggestions on how to more clearly communicate that, we are open to hearing them. Note that on GitHub, unlike Discord, mods not as visible in the sense that the GitHub UI doesn't apply color coding / etc. to mods the same way that Discord does. This is another way to say that mods are active in the issues that are open; however, depending on which thread and whether they called out their mod hat (like I did in my intro), they might look like regular users in that thread.
* Not all threads here require moderation "action", per se. This is called out on our [About](https://hachyderm.io/about) page under the section about reporting issues / interacting with mods. The short version: some issues here are suggestions and conversations which are left open while the discussion continues to keep it visible and in one place. Requests that require immediate moderator action, like "I need help filing a report" or "please upload this" or "service outage" (or whatever), are the ones that are prioritized and handled. Ones that require significant changes to architecture or process are moved to our internal tracker so we can put them as a ticket as part of that change.

Since this seems to be the conclusion of this thread, I'm going to go ahead and close it.

**Comment by helmingstay** [comment]
I'm actually quite surprised that this issue has been closed. I feel like it A) contains valuable discussion and thoughtful input from the community, and B) raises an important question that is broadly relevant to the community. I'm pleased to see the issues getting some attention at the moment (ended up here because https://hachyderm.io/about & friends were down), and I appreciated the detailed and thoughtful response from @quintessence. I also believe that the original issue (see title) has not been resolved, and is highly significant to the community at large and thus warrants ongoing community engagement.

**Comment by sindarina** [comment]
> * We appreciate the feedback on our current server policies. It's important to remember that Hachyderm is a free instance, and the admin team is comprised 100% of volunteers. While we strive to provide the best experience possible, and communicate as clearly as we can, it isn't realistic to expect the same uptime and guarantees as a large tech company. If that is the expectation, it's best to look for an instance that matches that for now.

@quintessence I am not expecting the same uptime and guarantees, and this isn't about downtime to begin with. This should be clear from the rest of the thread, and to have legitimate concerns brushed off and the issue closed when the problem that's been flagged has not been resolved feels like a cop-out, quite frankly. So does the "just move elsewhere". Like, really? Where would we go instead? Probably can't even reliably migrate, right now.

And, as I've already said, it's silly to expect everyone to be checking Nova's own feed, PLUS this issue tracker, PLUS the status page, PLUS the Discord, etc. Especially when it was made quite clear in earlier communication that things should go here, and not just be dropped into a Discord channel.

You have the tools available. What I am asking is for you to use them in a consistent manner that serves your userbase. Which will also reduce the load on your 100% volunteer team, as people are left with fewer questions, and can just go do something else because you are clearly communicating what is happening, when a resolution can be expected at the earliest, and so forth.

Signups are still not closed, from what I can tell. Is it really that difficult to be sensible, and at the very least not ADD to the already overloaded team, and infrastructure? This is, again, not rocket science. It is people with years of experience informing you of the mistakes you are making, and how you might go about solving them.

And last but not least; this isn't a free instance. We are asked for donations, to watch the Twitch stream, and we are putting in labour reporting these issues, into figuring out why Hachyderm isn't operating like it should. Every announcement made on the instance itself comes with a request for engagement, for affirmation.

Nothing about this is free, and dismissing the feedback because it's not universally positive should be considered problematic, and have anyone who is reading this be worried for the future health of this community. If you can't take it onboard when we're experiencing technical difficulties brought on by your own choices, how are we to trust that you'll manage when social problems inevitably hit?

**Comment by benwis** [comment]
👋 Mod here.
I support Quintessence in their decision to close this. At this time, we have no plans to limit signups. While it is definitely easier to limit growth at this point, we have decided not to. We appreciate the OP's attempt to bring this option to our attention. Hachyderm has grown substantially faster and farther than had been initially planned, and that has caused some growing pains, but we believe that it is still within our abilities to solve.

I do like the idea of a status page hosted elsewhere than the server instance as a single source of truth. I will explore that elsewhere.
