### ISSUE TITLE
Clarification of CW policies

### ISSUE THREAD

**Issue by daxelrod** [hachyderm/community#94]
Hello and thank you for making Hachyderm such a welcoming and well-run community!

I'm new to Mastadon in general and I'm trying to get my head around what I should use Content Warnings for. In particular https://hachyderm.io/about makes no explicit mention of them at all.

I understand from #35 that you're reluctant to have moderators wading into specifics around what needs to be CWed, but I'm wondering if there's perhaps a middle ground where it makes sense to outline general expectations while noting that you're asking people to follow them rather than enforcing them?

For example, I see some people CW-ing meta conversations about Twitter, or sports, or food, and I just want to make sure I'm following Rule 1 and adhering to general community practices, especially insofar as the rules are explicit about this being a safe space for LGTBQIA+ and neurodivergent folks.

Thank you!

**Comment by quintessence** [comment]
Hello!

No worries, happy to help :) The use of content warnings is less about strict rules like "use a CW when..." and abstractly have two main considerations: "use a CW whenever the psychologically safest option is to opt-in rather than default in" and "spoilers".

The latter is shorter to explain, so I'll do that one first. If you're watching a show, reading a book, etc. where a conversation would reveal spoilers that other users would reasonably be trying to avoid online then use the CW to protect the spoiler. Easy specific examples would be Game of Thrones when it was airing, Doctor Who, and so on. (Although, of course, not limited to Sci Fi and Fantasy :) )

For the opt-in, that takes a bit more to explain. The idea here is to center the safety of other's experience. For example if someone was sharing a video of yet another example of police violence against Black people, there would be a reason to assume that users should be opting into that sort of content (as broad reach with unknown users means by numbers you definitely have reach to users with PTSD, Black users who may have been in that situation or with loved ones who have, etc.). 

To summarize your specific examples:

* People are probably content warning posts about Twitter in general right now due to a mix of distaste for Twitter and potential trauma for any former Twitter employees who may be here, as the layoffs and mismanagement have been cruel
* Sports is probably CWed to avoid spoilers for game results _or_ avoid showing graphic injuries in the timeline if that's what's being shown
* Food is _generally_ CWed for awareness of people with eating disorders that may have strong, negative, reactions to food

In general we expect our users to use CWs responsibly. So this goes back to first and foremost asking the question "if I weren't posting this content, is this something I or an impacted group feel psychologically safer opting into or displaying by default" with "spoilers" as a handy, "off label", use of the feature.

Does that help?

**Comment by quintessence** [comment]
Going to close this one - note that I also create a usage doc for it:

https://github.com/hachyderm/community/blob/main/usage-docs/how-to-use-content-warnings.md
